### ISSUE TITLE
求大佬做个32位版

### ISSUE THREAD

**Issue by samondlee** [ericwang2006/docker_ttnode#1]
在hub.docker.com找了一圈大多是适配n1的arm64位docker

现在玩客云也可以 刷armbian挂甜糖了 就是没有32位镜像。。

大佬可否有空做一个

**Comment by ericwang2006** [comment]
手里没有设备,晚些时候做一个试试

**Comment by samondlee** [comment]
> 手里没有设备,晚些时候做一个试试

啊这，PDD 玩客云捡垃圾 炒鸡便宜32-5=27块一个

领月卡无门槛5元，然后 

短接刷入snail.img然后，（不确定需不需要用不用TTL调整启动顺序），用U盘刷入https://www.right.com.cn/forum/thread-4057492-1-1.html 插到靠网口的USB口

**Comment by ericwang2006** [comment]
可以测试一下了,增加了一个tag ericwang2006/ttnode:armv7
```
docker run -itd \
  -v /mnt/data/ttnode:/mnts \
  --name ttnode \
  --net=macnet --ip=192.168.2.2 --dns=114.114.114.114 --mac-address C2:F2:9C:C5:B2:94 \
  --privileged=true \
  --restart=always \
  ericwang2006/ttnode:armv7
```

**Comment by samondlee** [comment]
docker run -v /mnt/mnts1:/mnts -d --name ttnode1 --memory-swap -1 -m 256M --net=macnet --ip=192.168.1.245 --dns=114.114.114.114 --mac-address 66:02:D9:76:C0:12 -i -t --privileged=true --restart=always ericwang2006/ttnode:armv7 


docker exec -it ttnode1 /bin/bash    

/usr/node/ttnode -p /mnts


啊这，谢谢大佬绑定成功，火速恩山玩客云发帖
