### ISSUE TITLE
提现功能失效

### ISSUE THREAD

**Issue by 68cs** [ericwang2006/docker_ttnode#100]
![Xnip2022-01-12_07-59-17](https://user-images.githubusercontent.com/25496213/149040149-8a23322c-6f14-4cb3-bb7d-f51139469b95.png)
老大，更新一下镜像吧，提现需要短信验证码

**Comment by ericwang2006** [comment]
一般在应用中手动提现一次，下次自动提现就不会提示这个了，这是厂商的安全验证，无法解决。
