### ISSUE TITLE
请问这个项目的镜像还能用吗？

### ISSUE THREAD

**Issue by lzqd** [ericwang2006/docker_ttnode#101]
请问这个项目的镜像alpine版本还能用吗？
挂了5天了一点缓存都没有。

**Comment by ericwang2006** [comment]
如果手机应用上提示网络类型是0, 存储也正常, 就没问题, 一般是甜糖缓存调度的问题. 
用官方版本大概率也是同样的情况, 不过你可以试试官方的docker是否可以.
