### ISSUE TITLE
是否衍生出一个 helper 项目，仅提现和签到

### ISSUE THREAD

**Issue by lqzhgood** [ericwang2006/docker_ttnode#103]
主程序官方已经支持 x86 了。从稳定性和更新及时性考虑迁移官方主程序应该是最优解。
是否把其余的 签到 、 提现 等功能提取出来做一个 `ttnode_helper` 。

或者提供开关关闭PCDN？

**Comment by ericwang2006** [comment]
不新增项目了，我考虑加个环境变量吧。其实那个提现的脚本可以单独在Linux环境下跑。

**Comment by ericwang2006** [comment]
如果只想使用本镜像的自动收割星愿和自动提现的功能，可以把环境变量DISABLE_TTNODE设置成1，参考代码：
```
docker run -itd \
  -v /your/cache/path:/mnts \
  -e DISABLE_TTNODE=1 \
  -p 1043:1043 \
  --name ttnode \
  --restart=always \
  ericwang2006/ttnode:alpine
```
需要更新最新镜像
