### ISSUE TITLE
在x86 系统下无法开启upnp

### ISSUE THREAD

**Issue by HaneRo** [ericwang2006/docker_ttnode#11]

**Comment by HaneRo** [comment]
docker -v
Docker version 19.03.12, build 48a66213fe
 uname -a
Linux GRANBELM 5.4.86 #0 SMP Wed Jan 13 13:15:47 2021 x86_64 GNU/Linux
启动命令
docker run -itd \
  -v /mnt/sdb1/ttnode:/mnts \
  --name ttnode \
  --privileged=true \
  --restart=always \
  ericwang2006/ttnode
系统固件版本
OpenWrt Ipv6 S2021.01.14 by Sirpdboy / LuCI Master (git-20.343.54716-6fc079f)

**Comment by ericwang2006** [comment]
这个算是已知问题，x86架构下，无论网络模式用host还是macvlan都不可以，
我目前测试的基本规律是arm架构下大概率UPNP管用，
x86架构下尚未成功过，目前只能手动在路由器上映射端口。

**Comment by ericwang2006** [comment]
> docker -v
> Docker version 19.03.12, build 48a66213fe
> uname -a
> Linux GRANBELM 5.4.86 #0 SMP Wed Jan 13 13:15:47 2021 x86_64 GNU/Linux
> 启动命令
> docker run -itd
> -v /mnt/sdb1/ttnode:/mnts
> --name ttnode
> --privileged=true
> --restart=always
> ericwang2006/ttnode
> 系统固件版本
> OpenWrt Ipv6 S2021.01.14 by Sirpdboy / LuCI Master (git-20.343.54716-6fc079f)

现在最新的版本改用x86模拟arm32, 目前我自测是可以支持upnp了
