### ISSUE TITLE
如何限制甜糖缓存容量

### ISSUE THREAD

**Issue by someash** [ericwang2006/docker_ttnode#12]
这3天用了18g的空间，有点怕给我占满
（树莓派3b+，raspbian，tf卡128g）

**Comment by ericwang2006** [comment]
我能想到的方法有下面几个
1. 外接一个U盘，把U盘作为缓存目录
2. 制作一个固定大小的硬盘镜像文件ttnode.img，把这个镜像文件mount到一个目录做为缓存目录
3. Linux有磁盘配额设置，特定文件系统还支持按目录设置
我觉得门槛最低的就是弄一个U盘，跑甜糖64G的U盘基本够用了，太小效果不好，其他方法需要自行查找资料

**Comment by someash** [comment]
我觉得外接u盘可以，那怎么让甜糖缓存到u盘上？

**Comment by ericwang2006** [comment]
> 我觉得外接u盘可以，那怎么让甜糖缓存到u盘上？

你参考一下这篇挂载硬盘部分 http://www.right.com.cn/forum/forum.php?mod=viewthread&tid=4050539

**Comment by someash** [comment]
这是不是类似创造了一个环境，让默认的/mnts会指向u盘的/mnts？

**Comment by ericwang2006** [comment]
> 这是不是类似创造了一个环境，让默认的/mnts会指向u盘的/mnts？

你可以理解成本机的/mnts目录指向u盘这个设备的一个分区，更多信息要善用搜索，可尝试关键字 linux mount
