### ISSUE TITLE
配置文件和缓存位置

### ISSUE THREAD

**Issue by ppyuehui** [ericwang2006/docker_ttnode#13]
配置完以后配置文件和缓存位置都在/mnt下，手机客户端显示的缓存大小是/mnt的大小，第三行代码改成 `-v /mnts:/mnts \`后手机客户端显示成了挂载的/mnts大小

**Comment by ericwang2006** [comment]
-v /mnts:/mnts, 冒号前面的路径是宿主机路径, 这个路径的空间和手机客户端端的"存储大小","空闲存储"有关, 手机客户端的"缓存大小"是甜糖实际下载的缓存文件的大小

**Comment by ppyuehui** [comment]
原来如此，之前是我理解错了
