### ISSUE TITLE
兄弟，搬运别人的代码不用标明一下的？

### ISSUE THREAD

**Issue by yjce1314** [ericwang2006/docker_ttnode#14]
共同进步！

**Comment by ericwang2006** [comment]
自动收取星愿部分的SHELL脚本是参考了您在恩山帖子https://www.right.com.cn/forum/thread-4065542-1-1.html， 虽然做了一些改动和优化工作，但是的确是建立在您的优秀工作的基础之上的，我在帖子中做一下说明，在这里向你表示抱歉，希望得到您的谅解。

**Comment by ericwang2006** [comment]
> 兄弟，虽然我说开源，但是你直接搬运修改二次封装，不加以任何说明就不厚道了吧，搜你用户名也算是有头有脸的人，做起事情来这么马虎？ 请于下周三前做完该做的事。 --恩山网友

关于自动收取星愿的Shell脚本，已在我的恩山帖子https://www.right.com.cn/forum/thread-4059329-1-1.html 中添加了特别说明，在本仓库的Readme中也添加了说明，再次感谢您的优秀工作并向你表示抱歉。
