### ISSUE TITLE
请问如何添加定时任务，找不到config文件，谢谢

### ISSUE THREAD

**Issue by justincnn** [ericwang2006/docker_ttnode#16]
root@OpenWrt:~# docker exec -it ttnode /bin/bash
root@OpenWrt:/usr/node# ls
port.sh  port.txt  qr.sh  start.sh  ttnode  ttnode_task.sh
root@OpenWrt:/usr/node# 

具体如上面，找不到/config/crontab_list.sh这个文件，

**Comment by ericwang2006** [comment]
1. 如果你用的是docker, start.sh执行时会自动创建这个文件
2. 如果不是用的docker运行,  找/config/crontab_list.sh是没有意义的, 要直接编辑对应linux系统的crontab任务
一般是执行 crontab -e, 如果是openwrt在计划任务中直接增加就可了,程序具体路径根据自己情况修改
```
#自动更新
0 0 * * *  /usr/node/ttnode_task.sh update
#每日自动收取星愿
8 4 * * *  /usr/node/ttnode_task.sh report
#每周三自动提现
15 4 * * 3 /usr/node/ttnode_task.sh withdraw
```

**Comment by justincnn** [comment]
> 1. 如果你用的是docker, start.sh执行时会自动创建这个文件
> 2. 如果不是用的docker运行,  找/config/crontab_list.sh是没有意义的, 要直接编辑对应linux系统的crontab任务
>    一般是执行 crontab -e, 如果是openwrt在计划任务中直接增加就可了,程序具体路径根据自己情况修改
> 
> ```
> #自动更新
> 0 0 * * *  /usr/node/ttnode_task.sh update
> #每日自动收取星愿
> 8 4 * * *  /usr/node/ttnode_task.sh report
> #每周三自动提现
> 15 4 * * 3 /usr/node/ttnode_task.sh withdraw
> ```
> 
> 你应该是用的docker, 重点看看容器是否运行起来了, 看看docker的日志
> 3. **还有一种可能,你有没有用国内的docker镜像加速源, 国内的很多源缓存太老, 有可能当时的版本配置还没有改到/config下面, 老版本的配置文件在/usr/node下面的**

=====================
ttnode已经正常运行起来了，而且甜糖app也可以在第二天产生心愿，
问题是还是没法自动收取，主要的问题还是如上：
1.没有找到这个目录
2./user/node下也找不到，

**Comment by ericwang2006** [comment]
> > 1. 如果你用的是docker, start.sh执行时会自动创建这个文件
> > 2. 如果不是用的docker运行,  找/config/crontab_list.sh是没有意义的, 要直接编辑对应linux系统的crontab任务
> >    一般是执行 crontab -e, 如果是openwrt在计划任务中直接增加就可了,程序具体路径根据自己情况修改
> > 
> > ```
> > #自动更新
> > 0 0 * * *  /usr/node/ttnode_task.sh update
> > #每日自动收取星愿
> > 8 4 * * *  /usr/node/ttnode_task.sh report
> > #每周三自动提现
> > 15 4 * * 3 /usr/node/ttnode_task.sh withdraw
> > ```
> > 
> > 
> > 你应该是用的docker, 重点看看容器是否运行起来了, 看看docker的日志
> > 3. **还有一种可能,你有没有用国内的docker镜像加速源, 国内的很多源缓存太老, 有可能当时的版本配置还没有改到/config下面, 老版本的配置文件在/usr/node下面的**
> 
> =====================
> ttnode已经正常运行起来了，而且甜糖app也可以在第二天产生心愿，
> 问题是还是没法自动收取，主要的问题还是如上：
> 1.没有找到这个目录
> 2./user/node下也找不到，

我觉得大概率还是我说的第3种情况, 尝试删除原来的容器, 并运行下面代码重新创建容器
```
docker run -itd \
  -v /mnt/data/ttnode:/mnts \
  --name ttnode \
  --net=host \
  --privileged=true \
  --restart=always \
  ericwang2006/ttnode:v1.0.0.187
```
如果你用的是macvlan, 也可以把ericwang2006/ttnode 对应的改成ericwang2006/ttnode:v1.0.0.187
注意重新创建容器后ttnode的id可能会改变

**Comment by houfukude** [comment]
或许他只是单纯的想找 config 目录
试试
`docker exec -it ttnode /bin/bash`
`cd  /config/ `

**Comment by justincnn** [comment]
> > > 1. 如果你用的是docker, start.sh执行时会自动创建这个文件
> > > 2. 如果不是用的docker运行,  找/config/crontab_list.sh是没有意义的, 要直接编辑对应linux系统的crontab任务
> > >    一般是执行 crontab -e, 如果是openwrt在计划任务中直接增加就可了,程序具体路径根据自己情况修改
> > > 
> > > ```
> > > #自动更新
> > > 0 0 * * *  /usr/node/ttnode_task.sh update
> > > #每日自动收取星愿
> > > 8 4 * * *  /usr/node/ttnode_task.sh report
> > > #每周三自动提现
> > > 15 4 * * 3 /usr/node/ttnode_task.sh withdraw
> > > ```
> > > 
> > > 
> > > 你应该是用的docker, 重点看看容器是否运行起来了, 看看docker的日志
> > > 3. **还有一种可能,你有没有用国内的docker镜像加速源, 国内的很多源缓存太老, 有可能当时的版本配置还没有改到/config下面, 老版本的配置文件在/usr/node下面的**
> > 
> > 
> > =====================
> > ttnode已经正常运行起来了，而且甜糖app也可以在第二天产生心愿，
> > 问题是还是没法自动收取，主要的问题还是如上：
> > 1.没有找到这个目录
> > 2./user/node下也找不到，
> 
> 我觉得大概率还是我说的第3种情况, 尝试删除原来的容器, 并运行下面代码重新创建容器
> 
> ```
> docker run -itd \
>   -v /mnt/data/ttnode:/mnts \
>   --name ttnode \
>   --net=host \
>   --privileged=true \
>   --restart=always \
>   ericwang2006/ttnode:v1.0.0.187
> ```
> 
> 如果你用的是macvlan, 也可以把ericwang2006/ttnode 对应的改成ericwang2006/ttnode:v1.0.0.187
> 注意重新创建容器后ttnode的id可能会改变
=====================================
你好，请问你的docker hub上的内容都删除了？可以再分享下么？谢谢啊

**Comment by ericwang2006** [comment]
> > > > 1. 如果你用的是docker, start.sh执行时会自动创建这个文件
> > > > 2. 如果不是用的docker运行,  找/config/crontab_list.sh是没有意义的, 要直接编辑对应linux系统的crontab任务
> > > >    一般是执行 crontab -e, 如果是openwrt在计划任务中直接增加就可了,程序具体路径根据自己情况修改
> > > > 
> > > > ```
> > > > #自动更新
> > > > 0 0 * * *  /usr/node/ttnode_task.sh update
> > > > #每日自动收取星愿
> > > > 8 4 * * *  /usr/node/ttnode_task.sh report
> > > > #每周三自动提现
> > > > 15 4 * * 3 /usr/node/ttnode_task.sh withdraw
> > > > ```
> > > > 
> > > > 
> > > > 你应该是用的docker, 重点看看容器是否运行起来了, 看看docker的日志
> > > > 3. **还有一种可能,你有没有用国内的docker镜像加速源, 国内的很多源缓存太老, 有可能当时的版本配置还没有改到/config下面, 老版本的配置文件在/usr/node下面的**
> > > 
> > > 
> > > =====================
> > > ttnode已经正常运行起来了，而且甜糖app也可以在第二天产生心愿，
> > > 问题是还是没法自动收取，主要的问题还是如上：
> > > 1.没有找到这个目录
> > > 2./user/node下也找不到，
> > 
> > 
> > 我觉得大概率还是我说的第3种情况, 尝试删除原来的容器, 并运行下面代码重新创建容器
> > ```
> > docker run -itd \
> >   -v /mnt/data/ttnode:/mnts \
> >   --name ttnode \
> >   --net=host \
> >   --privileged=true \
> >   --restart=always \
> >   ericwang2006/ttnode:v1.0.0.187
> > ```
> > 
> > 
> > 如果你用的是macvlan, 也可以把ericwang2006/ttnode 对应的改成ericwang2006/ttnode:v1.0.0.187
> > 注意重新创建容器后ttnode的id可能会改变
> > =====================================
> > 你好，请问你的docker hub上的内容都删除了？可以再分享下么？谢谢啊

都在啊 https://hub.docker.com/r/ericwang2006/ttnode , 如果特别慢考虑挂梯子, 
或者参考我恩山帖子中离线导入镜像的方法https://www.right.com.cn/forum/thread-4059329-1-1.html

**Comment by justincnn** [comment]
> > > > > 1. 如果你用的是docker, start.sh执行时会自动创建这个文件
> > > > > 2. 如果不是用的docker运行,  找/config/crontab_list.sh是没有意义的, 要直接编辑对应linux系统的crontab任务
> > > > >    一般是执行 crontab -e, 如果是openwrt在计划任务中直接增加就可了,程序具体路径根据自己情况修改
> > > > > 
> > > > > ```
> > > > > #自动更新
> > > > > 0 0 * * *  /usr/node/ttnode_task.sh update
> > > > > #每日自动收取星愿
> > > > > 8 4 * * *  /usr/node/ttnode_task.sh report
> > > > > #每周三自动提现
> > > > > 15 4 * * 3 /usr/node/ttnode_task.sh withdraw
> > > > > ```
> > > > > 
> > > > > 
> > > > > 你应该是用的docker, 重点看看容器是否运行起来了, 看看docker的日志
> > > > > 3. **还有一种可能,你有没有用国内的docker镜像加速源, 国内的很多源缓存太老, 有可能当时的版本配置还没有改到/config下面, 老版本的配置文件在/usr/node下面的**
> > > > 
> > > > 
> > > > =====================
> > > > ttnode已经正常运行起来了，而且甜糖app也可以在第二天产生心愿，
> > > > 问题是还是没法自动收取，主要的问题还是如上：
> > > > 1.没有找到这个目录
> > > > 2./user/node下也找不到，
> > > 
> > > 
> > > 我觉得大概率还是我说的第3种情况, 尝试删除原来的容器, 并运行下面代码重新创建容器
> > > ```
> > > docker run -itd \
> > >   -v /mnt/data/ttnode:/mnts \
> > >   --name ttnode \
> > >   --net=host \
> > >   --privileged=true \
> > >   --restart=always \
> > >   ericwang2006/ttnode:v1.0.0.187
> > > ```
> > > 
> > > 
> > > # 如果你用的是macvlan, 也可以把ericwang2006/ttnode 对应的改成ericwang2006/ttnode:v1.0.0.187
> > > 注意重新创建容器后ttnode的id可能会改变
> > > 你好，请问你的docker hub上的内容都删除了？可以再分享下么？谢谢啊
> 
> 都在啊 https://hub.docker.com/r/ericwang2006/ttnode , 如果特别慢考虑挂梯子,
> 或者参考我恩山帖子中离线导入镜像的方法https://www.right.com.cn/forum/thread-4059329-1-1.html

jd挂机的docker还能分享么？

**Comment by ericwang2006** [comment]
jd挂机的docker的作者不是我

**Comment by justincnn** [comment]
> jd挂机的docker的作者不是我

嗯嗯，是我搞错了，甜糖挂上已经ok了，你的docker和端口设置，我恩山看我过用效果最好的，太感谢了，遇到你真好
