### ISSUE TITLE
甜糖重新创建容器后 uid并未发生变化

### ISSUE THREAD

**Issue by imi6** [ericwang2006/docker_ttnode#20]
甜糖重新创建容器后 uid并未发生变化，我重新绑定还是和以前的显示一样

**Comment by ericwang2006** [comment]
在arm架构下应该是没问题的，但是在x86架构下，重新创建容器，即使是同样的IP和mac地址，也会导致ttnode的uid变化
根据日志`utility.cpp(2511)-GetMacFromIfreq: ioctl error = 19!`推测，ttnode内部应该是使用ioctl函数来获取mac地址的，在qemu中不支持ioctl调用是个已知问题
可以参考[这里](https://github.com/multiarch/qemu-user-static/issues/101)，这个问题可以用下面的方法测试
```
$ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes
$ docker run --privileged -t -i armv7/armhf-ubuntu /bin/bash
$ apt-get update
$ apt-get install uml-utilities
$ tunctl
Unsupported ioctl: cmd=0x400454ca
TUNSETIFF: Function not implemented
```

**Comment by ericwang2006** [comment]
这个问题目前有了最新**进展**，经过多次测试发现ttnode的uid和以下因素同时相关
	- **hostname**
	- **网卡的mac地址**
 
	由于此前创建docker容器时并未指定hostname，所以每次创建容器都是随机的hostname，导致出现了随机的uid，目前已经修改了相关示例代码，创建容器时指定了hostname
