### ISSUE TITLE
面板能同一个内网部署的，用一个面板管理吗？

### ISSUE THREAD

**Issue by yumig** [ericwang2006/docker_ttnode#21]
比如我一台机器部署几十个Docker，通过一个面板进行管理

**Comment by ericwang2006** [comment]
即使部署很多docker容器一般也会在一个甜糖账号下集中管理,所以只要找其中一个容器设置好通知参数就可以了,没有必要每个容器都设置.

**Comment by yumig** [comment]
面板能单独部署就好了，自由选择，然后一个http://IP:1043这样管理

**Comment by ericwang2006** [comment]
我还是觉得这个需求比较少见,暂时不会考虑这个功能了.
