### ISSUE TITLE
优质网络，不过没有缓存生成

### ISSUE THREAD

**Issue by leungzw** [ericwang2006/docker_ttnode#22]
网络配置成功，APP上显示优质网络。
检查过宿主机上目录权限，已设为0777。
请教可能的原因还有哪些？

**Comment by ericwang2006** [comment]
最近甜糖没啥量, 如果确认缓存目录没问题, 大概率还是缓存调度的问题, 如果着急可以找找其他人共享出来的缓存复制到自己的目录.
