### ISSUE TITLE
x86 docker 已开upnp，公网IP，使用方法2(使用主机网络)，仍提示 “未配置网络”

### ISSUE THREAD

**Issue by City-Zero** [ericwang2006/docker_ttnode#23]
求解，该怎么解决

**Comment by ericwang2006** [comment]
如果确定使用的是最新版本镜像, 并且已经等待了足够长的时间, 那就是upnp没生效, 建议根据提示在路由器上手动做端口转发

**Comment by City-Zero** [comment]
@ericwang2006 忘了说了，用的 x86的openwrt的软路由拨号，没用路由器拨号， 这种应该不关upnp的事情吧

**Comment by ericwang2006** [comment]
> @ericwang2006 忘了说了，用的 x86的openwrt的软路由拨号，没用路由器拨号， 这种应该不关upnp的事情吧

你参考以下恩山大神的帖子https://www.right.com.cn/forum/thread-4048219-1-1.html
拉到下面看“桥接模式多开”部分

**Comment by DengYunJun** [comment]
老哥解决了吗？我也是这个问题
