### ISSUE TITLE
怎么在不修改设备id的前提下,更新镜像

### ISSUE THREAD

**Issue by qiao112** [ericwang2006/docker_ttnode#25]
现在使用的是老点的镜像,因为运行正常没有看到具体点的升级教程,不想轻举妄动,看到最近更新了挺多功能的还是想更新一下,奈何小白对docker不懂,

**Comment by qiao112** [comment]
还有我以前使用的容器是可以正常映射upnp的作者可以参考一下
https://registry.hub.docker.com/r/hc8903/ttnode-x86/

**Comment by qiao112** [comment]
自动使用加成卡功能能加个环境变量吗

**Comment by ericwang2006** [comment]
1. 目前最新的镜像upnp已经可以起作用了, 都是在x86架构下用qemu模拟arm32就可以正常工作(你提供的那个镜像也是模拟arm32),我原来的镜像是模拟arm64,有网友说这种模式效率好一些,我目前没有做详细测试,处于兼容性考虑暂时先采用模拟arm32这个方案(这也是其他镜像作者采用的模式)
2. 新版本是否使用加成卡可以在控制面板中设置
3. 升级镜像保持uid不变,要保证mac地址和hostname和原来一样,缓存目录也和原来一致
	- 记录原来的mac地址,hostname和缓存目录(hostname可以进入容器执行`hostname`命令获取)
	- 记录/config/config.json文件中的配置参数
	- 删除原来容器
	- 执行`docker pull ericwang2006/ttnode`获取最新镜像
	- 创建新的容器,mac地址,hostname和缓存目录要和原来一样
	- 即使uid发生了变化也不要紧,只要缓存目录不变,在手机客户端重新绑定新的uid就可以了
	- 更新了最新的镜像后,配置参数可以在控制面板中设置
	- 建议将/config目录映射到宿主机目录,下次再更新就不需要设置配置参数了

**Comment by qiao112** [comment]
> 1. 目前最新的版本upnp已经可以启动了，都是在x86架构下用qemu模拟arm32就可以正常工作（你提供的那个同时也是模拟arm32），我原来的完全是模拟arm64，有网友说这种模式效率好一些，我目前没有做详细测试，出于兼容性考虑暂时先采用模拟arm32这个方案（这也是其他所有人作者采用的模式）
> 2. 新版本是否使用加成卡可以在控制面板中设置
> 3. 升级升级保持uid不变，要保证mac地址和主机名和原来一样，缓存目录也和原来一致
>    
>    * 记录原来的mac地址，主机名和缓存目录（主机名可以进入容器执行`hostname`命令获取）
>    * 记录/config/config.json文件中的配置参数
>    * 删除原来容器
>    * 执行`docker pull ericwang2006/ttnode`获取最新数据
>    * 创建新的容器，mac地址，主机名和缓存目录要和原来一样
>    * 即使uid发生了变化也不要紧，一旦缓存目录不变，在手机客户端重新绑定新的uid就可以了
>    * 更新了最新的补充后，配置参数可以在控制面板中设置
>    * 建议将/ config目录映射到主机机目录，下次再更新就不需要设置配置参数了

现在保证mac地址和主机名以及缓存目录不变的情况下uid也是不会变的是吗

**Comment by qiao112** [comment]
获取出来的hostname再重新创建之后需要修改吗

**Comment by qiao112** [comment]
由于此前创建docker容器时并未指定hostname，所以每次创建容器都是随机的hostname，导致出现了随机的uid，目前已经修改了相关示例代码，创建容器时指定了hostname     这句话中指定hostname会自动指定删除之前容器的hostname吗

**Comment by ericwang2006** [comment]
我觉得我写得够清楚了, 你还是自己多试试吧, 很多疑问实际操作一下就解决了
另外我觉得uid即使变了也不是什么大事情, 如果你很在意uid, 那么我建议你在其他测试机上先练习一下
