### ISSUE TITLE
docker-compose里面的macvlan没看懂........

### ISSUE THREAD

**Issue by goukey** [ericwang2006/docker_ttnode#26]
就是设置ip的部分没看明白
ip段应该填宿主机同ip段还是不同？比如我宿主机是192.168.1.15，那macvlan里应该写192.168.1.x还是192.168.2.x ？？？

另外docker-compose就不用开混杂吧？

**Comment by ericwang2006** [comment]
1. macvlan的网段要和宿主机一致(除非你是高级用户,知道自己要做什么), 比如你的宿主机是192.168.1.15,  macvlan的网段就是192.168.1.0/24 
2. 混杂一般不用开,  你可以根据自己的情况, 不能正常工作再开, 我这里无论任何模式不开混杂都可以正常工作

**Comment by goukey** [comment]
macvlan设置192.168.1网段了，不过貌似还得把1043从容器映射出去，不然ip:1043访问不了，建议compose里加入
`    ports:
      - "1043:1043"`

**Comment by ericwang2006** [comment]
> macvlan设置192.168.1网段了，不过貌似还得把1043从容器映射出去，不然ip:1043访问不了，建议compose里加入
> ` ports: - "1043:1043"`

如果你认为需要端口映射,可能你还没有认真看我的README

**Comment by goukey** [comment]
我这儿无论是macvlan还是host方式，ip:1043一律失败，只有映射才能连接，不知道为什么

**Comment by ericwang2006** [comment]
你是不是主路由上跑的docker? 
如果是这种情况你参考一下恩山大神的帖子https://www.right.com.cn/forum/thread-4048219-1-1.html
拉到下面看“桥接模式多开”部分

**Comment by goukey** [comment]
我是docker for windows............

**Comment by ericwang2006** [comment]
> 我是docker for windows............

没研究过，可能帮不到你了，你自己再查一下资料吧。
