### ISSUE TITLE
执行 ./usr/node/ttnode -p /mnts后有报错，麻烦大神看下

### ISSUE THREAD

**Issue by fzyejy** [ericwang2006/docker_ttnode#27]
> ./usr/node/ttnode -p /mnts

执行缓存路径指定后报错误
>version: 1.0.0.188
>2021-02-25 14:41:03.119 utility.cpp(2511)-GetMacFromIfreq: ioctl error = 19!
>2021-02-25 14:41:03.121 utility.cpp(2511)-GetMacFromIfreq: ioctl error = 19!
>uid = 145461c77e71b03b2d28897fbe5669ed
>2021-02-25 14:41:03.130 node [145461c77e71b03b2d28897fbe5669ed,/mnts] exist,error = 11
请问对运行有影响吗？ 还是我哪里配置有问题，谢谢

运行环境
X86 
操作系统
centos7.6
内核
5.4.100-1.el7.elrepo.x86_64

启动脚本
docker run -itd \
  -v /app/docker/ttnode:/mnts \
  --name ttnode \
  --hostname ttnode1 \
  --net=host \
  --privileged=true \
  --restart=always \
  ericwang2006/ttnode

**Comment by ericwang2006** [comment]
运行容器前/app/docker/ttnode是空目录吗？试试换个缓存目录行不行
