### ISSUE TITLE
登录接口貌似404了，设置cookie收不到验证码

### ISSUE THREAD

**Issue by Hellogu** [ericwang2006/docker_ttnode#28]

**Comment by ericwang2006** [comment]
我这里测试还是正常状态

**Comment by Hellogu** [comment]
我是在Coreelec里运行的docker，方法二，原来是curl后没有返回{"msg":"","errCode":0,"data":null}，加了-k参数解决了，谢谢老司机

**Comment by ericwang2006** [comment]
> 我是在Coreelec里运行的docker，方法二，原来是curl后没有返回{"msg":"","errCode":0,"data":null}，加了-k参数解决了，谢谢老司机

出于安全考虑我全部用的https访问的接口,没有用http. 本来以为在docker里面跑这套代码没有证书的问题,因为docker环境相对独立,我在docker里安装了ca-certificates就不会报错了, 没想到还是有这个问题.
另外麻烦帮我看一下宿主机的时间是否正确.

**Comment by Hellogu** [comment]
![image](https://user-images.githubusercontent.com/19606259/110441649-f83c2980-80f4-11eb-801e-86561fe327be.png)
时间与宿主机一致的

**Comment by Ukenn2112** [comment]
> 我是在Coreelec里运行的docker，方法二，原来是curl后没有返回{"msg":"","errCode":0,"data":null}，加了-k参数解决了，谢谢老司机

我也遇见同样问题一直无法收到验证码，请问是如何解决的，谢谢
