### ISSUE TITLE
双宽带配置

### ISSUE THREAD

**Issue by hx210** [ericwang2006/docker_ttnode#29]
我有电信300m和100m,现在我已经配置好了300m宽带，我想把它们都利用上，通过docker，可以的话，你能告诉我怎么做吗。我是想net=macnet --ip 172.111.0.3 --dns=119.29.29.29。然后桥接到我第二个宽带的接口是通过100m的路由器分配的地址。然后100m路由器配置端口转发，但在这以上docker的访问控制里的接口设置就得添加100m的吗？这会导致我原来部署好的甜糖变成多个出口ip。求解如何在单臂路由设备上通过另一个宽带100m的接口来跑甜糖

**Comment by ericwang2006** [comment]
只能提供一下思路给你参考
如果是多个路由器拨号, 创建不同的macvlan, macvlan的网关分别指向不同的路由器的IP
如果是单个路由器拨号,考虑使用iptables分流

**Comment by hx210** [comment]
谢谢
