### ISSUE TITLE
运行时内存一直增加，ttnode被kill，然后ttnode一直restarting

### ISSUE THREAD

**Issue by 86jacklee** [ericwang2006/docker_ttnode#3]

**Comment by ericwang2006** [comment]
你是什么设备, 内存多少? 目前我用的x86虚拟机,3G内存,同时跑3个容器比较稳定.

**Comment by azureology** [comment]
```
$ docker logs ttnode| grep ttnode
[2020-12-26 18:00:46] ttnode进程不存在,启动ttnode
[2020-12-26 18:04:33] ttnode进程不存在,启动ttnode
[2020-12-26 18:42:57] ttnode进程不存在,启动ttnode
[2020-12-26 20:17:32] ttnode进程不存在,启动ttnode
[2020-12-26 20:56:21] ttnode进程不存在,启动ttnode
[2020-12-26 21:30:43] ttnode进程不存在,启动ttnode
[2020-12-26 21:44:59] ttnode进程不存在,启动ttnode
[2020-12-26 21:48:41] ttnode进程不存在,启动ttnode
[2020-12-26 22:24:09] ttnode进程不存在,启动ttnode
[2020-12-26 22:40:15] ttnode进程不存在,启动ttnode
```

树莓派3b测试同样有此问题，反映客户端在线率偏低。
配置4核armv7内存1GB

**Comment by ericwang2006** [comment]
限制一下内存试试吧
docker update ttnode --memory-swap -1 -m 700M
然后重启一下容器

**Comment by 86jacklee** [comment]
> 你是什么设备, 内存多少? 目前我用的x86虚拟机,3G内存,同时跑3个容器比较稳定.

x86虚拟机,2G内存,1个容器.

**Comment by azureology** [comment]
> 限制一下内存试试吧
> docker update ttnode --memory-swap -1 -m 700M
> 然后重启一下容器,具体限制到多少合适要自己测试一下

感谢！限制700M没再崩溃，问题解决。

**Comment by 86jacklee** [comment]
ok，我试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "azureology"<notifications@github.com&gt;; 
发送时间: 2020年12月27日(星期天) 晚上7:49
收件人: "ericwang2006/docker_ttnode"<docker_ttnode@noreply.github.com&gt;; 
抄送: "我是一个卒子"<1632387183@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ericwang2006/docker_ttnode] 运行时内存一直增加，ttnode被kill，然后ttnode一直restarting (#3)





  
限制一下内存试试吧
 docker update ttnode --memory-swap -1 -m 700M
 然后重启一下容器,具体限制到多少合适要自己测试一下
  
感谢！限制700M没再崩溃，问题解决。

**Comment by ericwang2006** [comment]
> > 你是什么设备, 内存多少? 目前我用的x86虚拟机,3G内存,同时跑3个容器比较稳定.
> 
> x86虚拟机,2G内存,1个容器.

另外进入容器,执行
```
# /usr/node/ttnode -v
version: 1.0.0.172
```
看看ttnode的版本是不是1.0.0.172, 如果是老一点的镜像,ttnode会自动升级,会不会是自动升级一直失败导致不断重启?
如果ttnode版本不是1.0.0.172,建议删除镜像重新拉取最新的试一下.

**Comment by 86jacklee** [comment]
没问题，是1.0.0.172，我限制内存再看看吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ericwang2006"<notifications@github.com&gt;; 
发送时间: 2020年12月27日(星期天) 晚上7:55
收件人: "ericwang2006/docker_ttnode"<docker_ttnode@noreply.github.com&gt;; 
抄送: "我是一个卒子"<1632387183@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ericwang2006/docker_ttnode] 运行时内存一直增加，ttnode被kill，然后ttnode一直restarting (#3)





   
你是什么设备, 内存多少? 目前我用的x86虚拟机,3G内存,同时跑3个容器比较稳定.
  
x86虚拟机,2G内存,1个容器.
  
另外进入容器,执行
 # /usr/node/ttnode -v version: 1.0.0.172  
看看ttnode的版本是不是1.0.0.172, 如果是老一点的镜像,ttnode会自动升级,会不会是自动升级一直失败导致不断重启?
 如果ttnode版本不是1.0.0.172,建议删除镜像重新拉取最新的试一下.

**Comment by someash** [comment]
> > 限制一下内存试试吧
> > docker update ttnode --memory-swap -1 -m 700M
> > 然后重启一下容器,具体限制到多少合适要自己测试一下
> 
> 感谢！限制700M没再崩溃，问题解决。

树莓派好像默认不打开swap限制功能，你是怎么打开这个功能的，我不太会。。。还有这个问题能不能通过扩容swap到2g来解决？
