### ISSUE TITLE
在r2s的openwrt 的docker下运行失败了- -

### ISSUE THREAD

**Issue by rheatin** [ericwang2006/docker_ttnode#30]
报错信息如下：Containers: start ttnode...code:500 OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:338: getting the final child's pid from pipe caused: EOF: unknown

openwrt版本：Powered by LuCI openwrt-18.06 branch (git-21.050.58382-e3dad08) / ArgonTheme v1.7.1 / ImmortalWrt 18.06-SNAPSHOT r0-55d533fb 

openwrt的docker版本：20.10.2-1
openwrt的dockerman版本：v0.4.7-leanmod

**Comment by ericwang2006** [comment]
openwrt镜像能提供一下吗？

**Comment by rheatin** [comment]
谢谢大佬关注

https://cloud.189.cn/t/6V3MnaBN7bum（访问码：7ssi）

（之前邮包传被据收了= =

**Comment by rheatin** [comment]
谢谢大佬关注~~~😃
https://cloud.189.cn/t/6V3MnaBN7bum（访问码：7ssi）


（之前邮包被拒收了- -


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ericwang2006/docker_ttnode"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月4日(星期四) 下午5:49
收件人:&nbsp;"ericwang2006/docker_ttnode"<docker_ttnode@noreply.github.com&gt;;
抄送:&nbsp;"不甜不要钱，而已"<125110985@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ericwang2006/docker_ttnode] 在r2s的openwrt 的docker下运行失败了- - (#30)





 
openwrt镜像能提供一下吗？

**Comment by ericwang2006** [comment]
不好意思, 没看清你的描述, 以为是x86的设备呢, 目前我没有r2s这个设备, 可能不能具体帮到你了, 简单搜了一下这个错误信息, 可能和系统内核有关, 建议你换一个其它的openwrt镜像或者找个armbian的镜像测试一下.

**Comment by rheatin** [comment]
> 不好意思, 没看清你的描述, 以为是x86的设备呢, 目前我没有r2s这个设备, 可能不能具体帮到你了, 简单搜了一下这个错误信息, 可能和系统内核有关, 建议你换一个其它的openwrt镜像或者找个armbian的镜像测试一下.

没关系，我用qnap装吧，依然谢谢你
