### ISSUE TITLE
储存大小只显示1GB

### ISSUE THREAD

**Issue by xz950211** [ericwang2006/docker_ttnode#32]
32GB u盘只显示1GB，都是按照教程走的，之前用的“会赚钱的软路由]Openwrt下挂docker版甜糖CDN 支持X86/ARM设备 -保姆级原创教程”，这个帖子没问题，请问怎么解决

**Comment by ericwang2006** [comment]
重点看一下缓存目录的映射是否正确,  另外关注一下U盘分区是否正确挂载到了缓存目录.
