### ISSUE TITLE
3867U OpenWrt5.4.101

### ISSUE THREAD

**Issue by coxlxd** [ericwang2006/docker_ttnode#33]
Intel(R) Celeron(R) CPU 3867U @ 1.80GHz : 2 Core 2 Thread (CpuMark : 26135.249918 Scores)
--
报错

stdout: No binfmt support in the kernel.
stdout:   Try: '/sbin/modprobe binfmt_misc' from the host

**Comment by ericwang2006** [comment]
x86架构下的镜像已经内建了qemu的支持, 这种情况大概率是你使用了国内的docker镜像服务器,拉下来的不是最新版本
建议直接使用 ericwang2006/ttnode:v1.0.0.188 试一下

**Comment by coxlxd** [comment]
已部署，只是不停重启。日志提示 ttnode进程不存在

stdout: 如果觉得还有点用，麻烦用一下我的邀请码631441，有加成卡15张，我也有推广收入
stdout: 请在浏览器访问【http://10.1.1.3:1043】甜糖控制面板，在这里可以扫码添加客户端，也可进行通知设置
stdout: 如有任何担心，可将此【*****************】UID复制，选择您信任的工具生成二维码并用甜糖客户端扫描添加
stdout: [2021-03-11 23:29:47] 正在获取端口信息...
stdout: [2021-03-11 23:30:07] ttnode进程不存在,启动ttnode
stdout: version: 1.0.0.188
stdout: uid =******
stdout: 2021-03-11 23:30:07.336 storage [/mnts],dev [/mnts] cannot access

**Comment by coxlxd** [comment]
> x86架构下的镜像已经内建了qemu的支持, 这种情况大概率是你使用了国内的docker镜像服务器,拉下来的不是最新版本
> 建议直接使用 ericwang2006/ttnode:v1.0.0.188 试一下

已部署，只是不停重启。日志提示 ttnode进程不存在

stdout: 如果觉得还有点用，麻烦用一下我的邀请码631441，有加成卡15张，我也有推广收入
stdout: 请在浏览器访问【http://10.1.1.3:1043】甜糖控制面板，在这里可以扫码添加客户端，也可进行通知设置
stdout: 如有任何担心，可将此【***********】UID复制，选择您信任的工具生成二维码并用甜糖客户端扫描添加
stdout: [2021-03-11 23:29:47] 正在获取端口信息...
stdout: [2021-03-11 23:30:07] ttnode进程不存在,启动ttnode
stdout: version: 1.0.0.188
stdout: uid =
stdout: 2021-03-11 23:30:07.336 storage [/mnts],dev [/mnts] cannot access
