### ISSUE TITLE
多个docker容器同时运行，只有一个跑流量

### ISSUE THREAD

**Issue by Always67** [ericwang2006/docker_ttnode#35]
使用的威联通453B mini。j3455的U 16G内存，威联通虚拟机安装openwrt作为主路由，四拨成功上传带宽叠加。在威联通中直接使用container运行三个甜糖，使用负载均衡对应不同ip，镜像缓存目录也挂载到了不同目录。
三个节点都显示优质节点，但是每次都只有一个容器有上传，另外两个就是0，三个容器交替上传。而且跑上传的那个容器还会显示离线，实际从路由看是有上传的，是不支持单线多拨吗？

**Comment by ericwang2006** [comment]
目前甜糖不支持多线汇聚, 建议通过路由器的规则, 保证每个实例只走一条线路.
