### ISSUE TITLE
每次重新启动,有个udp端口会变

### ISSUE THREAD

**Issue by ioxuy** [ericwang2006/docker_ttnode#37]
网络类型为3,不知道是不是这个端口变了的原因
![CleanShot 2021-03-15 at 11 21 57@2x](https://user-images.githubusercontent.com/7322644/111099630-dfae9200-8580-11eb-9d2f-f6ce3bc5fcfb.png)

**Comment by ericwang2006** [comment]
这个经常变的端口应该是没有被用于数据传输的(如果UPNP起作用,你可以发现这个端口并没有自动映射),只是这个端口没什么特征,不方便在脚本中不显示

**Comment by ioxuy** [comment]
> 这个经常变的端口应该是没有被用于数据传输的(如果UPNP起作用,你可以发现这个端口并没有自动映射),只是这个端口没什么特征,不方便在脚本中不显示, 网络类型是3应该不是这个端口的问题, 只要保证不变的那几个端口通就可以了

是这样的,后来重新检测就是0了,跟这个端口是没关系,谢谢回复
