### ISSUE TITLE
爱快软路由Docker跑甜糖的问题

### ISSUE THREAD

**Issue by Xuchengen** [ericwang2006/docker_ttnode#38]
在爱快软路由中跑docker甜糖有3个问题
1.缓存大小一直为0
2.持续运行24小时以上可能会出现离线状态并且持续好几个小时依然是离线状态重启docker中的甜糖服务则重新上线。
3.给docker中的甜糖服务分配512M内存持续运行24小时以上内存占用380M但是缓存大小一直为0。甜糖直接使用内存对外提供服务？

**Comment by ericwang2006** [comment]
1.很多人遇到缓存一直是0,甜糖调度问题,无解
2和3 看看是不是内存太少, 甜糖服务比较占内存,目前我收到的反馈有限制到700M内存正常运行的
抱歉暂时没精力测试多种软路由系统的兼容性,先尝试增加内存吧

**Comment by ericwang2006** [comment]
爱快今天测试了一下，由于权限问题(主要是作者水平太差)，目前不能正常运行

**Comment by Xuchengen** [comment]
爱快docker挂甜糖我是参考的这篇博文：https://www.5v13.com/mesh/28836.html
结论是可以正常跑量但偶尔会有崩溃的现象（可能是分配的512M内存不够）。
3月20-21号在腾讯云服务器和黑群晖中折腾你的最新版目前表现是正常0状态，腾讯云上跑的已经有缓存文件（5M的小水管没什么搞头后面会撤掉）。
[image: Snipaste_2021-03-21_23-03-46.png]

ericwang2006 ***@***.***> 于2021年3月21日周日 下午4:47写道：

**Comment by ericwang2006** [comment]
主要是ipdbcf报错的问题,可以尝试进入docker的控制台, 执行
`cd /mnts && echo -e  "#!/bin/bash\necho ipdbcf" > ipdbcf && chmod +x ipdbcf`
或许可以消除错误提示
