### ISSUE TITLE
请问，我这里提示：ttnode进程不存在,启动ttnode........

### ISSUE THREAD

**Issue by mimokini** [ericwang2006/docker_ttnode#39]
===================================================================
-18 02:37:22] 正在获取端口信息...
annot create /proc/sys/net/core/wmem_max: Directory nonexistent
-18 02:37:42] ttnode进程不存在,启动ttnode
1.0.0.188
257fee0a85bc------------be1b
===================================================================

ericwang2006.github.io/docker_ttnode/qrgen.htm?str=21257fee0a85bc8f------------be1b

===================================================================
-18 02:37:43] 正在获取端口信息...
annot create /proc/sys/net/core/wmem_max: Directory nonexistent
-18 02:38:03] 正在获取端口信息...
-18 02:38:23] 正在获取端口信息...
===================================================================
-18 02:38:43] 如果UPNP失效，请在路由器上对下列端口做转发

8
8
2
2
===================================================================

**Comment by ericwang2006** [comment]
只要最后提示出端口信息就说明正常启动了

**Comment by pys078** [comment]
你这个是目录没挂载

**Comment by ericwang2006** [comment]
> 你这个是目录没挂载

`cannot create /proc/sys/net/core/wmem_max: Directory` 这个报错是正常的(参看README的已知问题), 他这个实际上已经正常运行了

**Comment by pys078** [comment]
> > 你这个是目录没挂载
> 
> `cannot create /proc/sys/net/core/wmem_max: Directory` 这个报错是正常的(参看README的已知问题), 他这个实际上已经正常运行了

这样子啊
