### ISSUE TITLE
请问作者有考虑增加自动收取心愿的功能吗？

### ISSUE THREAD

**Issue by yubanmeiqin9048** [ericwang2006/docker_ttnode#4]

**Comment by ericwang2006** [comment]
这个确实可以有，等有空看看

**Comment by ericwang2006** [comment]
> _No description provided._

发现这位大神已经做得比较完善了，你可以参考一下他的代码，docker版也有
https://www.right.com.cn/forum/thread-4048219-1-1.html
https://github.com/744287383/AutomationTTnode

**Comment by yubanmeiqin9048** [comment]
> > _No description provided._
> 
> 发现这位大神已经做得比较完善了，你可以参考一下他的代码，docker版也有
> https://www.right.com.cn/forum/thread-4048219-1-1.html
> https://github.com/744287383/AutomationTTnode

感谢回答
