### ISSUE TITLE
多开怎么修改1043端口号？

### ISSUE THREAD

**Issue by sjkhsl** [ericwang2006/docker_ttnode#40]
多开怎么修改1043端口号？

**Comment by ericwang2006** [comment]
多开建议使用macvlan, 每个容器有不同的IP, 端口号不会冲突(详见README)
如果禁用网页控制面板参看环境变量说明

**Comment by sjkhsl** [comment]
> 多开建议使用macvlan，每个容器有不同的IP，端口号不会冲突（详见自述）
> 如果禁用网页控制面板参看环境变量说明

哦哦，明白了！没反应过来！
