### ISSUE TITLE
每次重启，端口号都会变！

### ISSUE THREAD

**Issue by sjkhsl** [ericwang2006/docker_ttnode#41]
我是使用的端口转发，然后甜糖只要重启，端口号就会变！怎么固定？

**Comment by knight-666** [comment]
还会报错sh: 1: /mnts/ipdbcf: Exec format error
sh: 1: /mnts/ipdbcf: Exec format error
sh: 1: /mnts/ipdbcf: Exec format error
sh: 1: /mnts/ipdbcf: Exec format error

**Comment by ericwang2006** [comment]
今天(2020.3.19)官方升级了新版本, 导致报错, 暂时尝试在宿主机执行
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
然后再重启容器

**Comment by dy2898** [comment]
sh: write error: Invalid argument
Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /usr/bin/qemu-arm-static as binfmt interpreter for arm
sh: write error: Invalid argument
Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
sh: write error: Invalid argument
Setting /usr/bin/qemu-sparc-static as binfmt interpreter for sparc
群晖运行qemu-user-static --reset -p yes报错

**Comment by dy2898** [comment]
> 今天（2020.3.19）官方升级了新版本，导致报错，暂时尝试在
> 主机机执行docker run --rm --privileged multiarch / qemu-user-static --reset -p yes
> 然后再重启容器

sh: write error: Invalid argument
Setting /usr/bin/qemu-alpha-static as binfmt interpreter for alpha
Setting /usr/bin/qemu-arm-static as binfmt interpreter for arm
sh: write error: Invalid argument
Setting /usr/bin/qemu-armeb-static as binfmt interpreter for armeb
sh: write error: Invalid argument
Setting /usr/bin/qemu-sparc-static as binfmt interpreter for sparc
群晖运行qemu-user-static --reset -p yes报错

**Comment by tianya908** [comment]
utility.cpp(2513)-GetMacFromIfreq: ioctl error = 19!
 报错怎么弄

**Comment by ericwang2006** [comment]
不需要运行docker run --rm --privileged multiarch/qemu-user-static --reset -p yes了, 
更新2021.3.20 9:00:00以后的最新版本再试一下

**Comment by ericwang2006** [comment]
更新到最新版本(GMT+8 2021-03-21 10:00:00后发布)镜像测试以下，具体情况参看README特别说明。

**Comment by knight-666** [comment]
现在还是重启端口就变了，这个能解决吗?

**Comment by knight-666** [comment]
现在还是重启端口就变了，这个能解决吗? 而且每次upnp设置的都是上一次甜糖的端口地址

**Comment by ericwang2006** [comment]
> 现在还是重启端口就变了，这个能解决吗? 而且每次upnp设置的都是上一次甜糖的端口地址

端口号应该只和.yfnode目录里面的配置文件有关,
重点应该分析一下docker启动的时候缓存目录是否已经正常挂载
这个问题我没有复现过, 无法帮到你

**Comment by knight-666** [comment]
> > 现在还是重启端口就变了，这个能解决吗? 而且每次upnp设置的都是上一次甜糖的端口地址
> 
> 端口号应该只和.yfnode目录里面的配置文件有关,
> 重点应该分析一下docker启动的时候缓存目录是否已经正常挂载
> 这个问题我没有复现过, 无法帮到你

谢谢，我排查看看

**Comment by dfc643** [comment]
同端口每次都变，而且upnp不生效（在openwrt）
