### ISSUE TITLE
请问 爱快docker运行无法获取UID，无法绑定，怎么回事

### ISSUE THREAD

**Issue by woodywudy** [ericwang2006/docker_ttnode#42]
=======爱快docker运行无法获取UID。
=======日志提示：
root@ttnode:/usr/node# ./start.sh

[ ok ] Starting periodic command scheduler: cron.
[2021-03-20 12:33:10] ttnode进程不存在,启动ttnode
./start.sh: line 93: /usr/node/ttnode: cannot execute binary file: Exec format error
/usr/node/qr.sh: line 21: /usr/node/ttnode: cannot execute binary file: Exec format error
获取二维码失败
[2021-03-20 12:33:10] 正在获取端口信息...

=======容器IP:1043 页面也是无法获取 提示 玩命加载中

**Comment by Always67** [comment]
威联通docker遇到同样问题

**Comment by ericwang2006** [comment]
最近甜糖升级带来的一系列问题,等明天我会发个详细说明

**Comment by ericwang2006** [comment]
更新到最新版本(GMT+8 2021-03-21 10:00:00后发布)镜像测试以下，具体情况参看README特别说明。

**Comment by Always67** [comment]
威联通运行正常了，日志有个
sh: 1: /mnts/ipdbcf: Permission denied                                                                                         
sh: 1: /mnts/ipdbcf: Permission denied                                                                                         
sh: 1: /mnts/ipdbcf: Exec format error                                                                                         
sh: 1: /mnts/ipdbcf: Exec format error                                                                                         
sh: 1: /mnts/ipdbcf: Exec format error                                                                                         
sh: 1: /mnts/ipdbcf: Exec format error                                                                                         
sh: 1: /mnts/ipdbcf: Exec format error                                                                                         
sh: 1: /mnts/ipdbcf: Exec format error 
不过已经跑起来了

**Comment by ericwang2006** [comment]
> 威联通运行正常了，日志有个
> sh: 1: /mnts/ipdbcf: Permission denied
> sh: 1: /mnts/ipdbcf: Permission denied
> sh: 1: /mnts/ipdbcf: Exec format error
> sh: 1: /mnts/ipdbcf: Exec format error
> sh: 1: /mnts/ipdbcf: Exec format error
> sh: 1: /mnts/ipdbcf: Exec format error
> sh: 1: /mnts/ipdbcf: Exec format error
> sh: 1: /mnts/ipdbcf: Exec format error
> 不过已经跑起来了
> ps:使用的是最新版的离线镜像
> pps:估计是因为我mnts挂载的还是之前的目录，不过能正常跑就满足了

威联通能不能进入容器的命令行界面? 如果能执行下面命令,有可能不再报错
```
cd /mnts && echo -e  "#!/bin/bash\necho ipdbcf" > ipdbcf && chmod +x ipdbcf
```

**Comment by Always67** [comment]
感谢大佬，可以执行命令，但是现在报另一个错误
/mnts/ipdbcf: 1: /mnts/ipdbcf: -e: not found

/mnts/ipdbcf: 1: /mnts/ipdbcf: -e: not found

**Comment by ericwang2006** [comment]
你看一下/mnts/ipdbcf这个文件
```
#!/bin/bash
echo ipdbcf
```
如果不是上面的内容你手动改一下试试, 或者再更新一下我最新的镜像试试

**Comment by Always67** [comment]
文件是存在的，我把上面的命令中的-e去掉之后，现在不报错了。
现在试一下最新镜像

**Comment by FengNning** [comment]
爱快docker是不是不能用

**Comment by ericwang2006** [comment]
> 爱快docker是不是不能用

主要是权限不够, 不能禁止ipdbcf, 运行一段时间就都是这个进程了, 目前肯定是用不爽
而且这个进程的作用目前尚不明确,总之不仅爱快, 用x86架构下的方案本身不是完美方案

**Comment by ericwang2006** [comment]
> 文件是存在的，我把上面的命令中的-e去掉之后，现在不报错了。
> 现在试一下最新镜像

```
cd /mnts && echo '#!/bin/bash' > ipdbcf && chmod +x ipdbcf
echo '#!/bin/bash' >/usr/bin/killall && chmod +x /usr/bin/killall
```
干脆这样一步到位修复最近2个报错

**Comment by ericwang2006** [comment]
目前新版本经测试已经不会自动下载**ipdbcf**了，我测试爱快已经可以正常运行了
