### ISSUE TITLE
无法收到验证码

### ISSUE THREAD

**Issue by Ukenn2112** [ericwang2006/docker_ttnode#43]
https://github.com/ericwang2006/docker_ttnode/issues/28

出现类似问题，一直在网页面板上填入手机号无法获取验证码

使用环境：Raspberry Pi 4b Ubuntu 18.04

**Comment by ericwang2006** [comment]
进入容器， 执行 `curl -s -X POST "https://tiantang.mogencloud.com/web/api/login/code?phone=你的手机号码"`
看看错误日志是什么

**Comment by Ukenn2112** [comment]
> 进入容器， 执行 `curl -s -X POST "https://tiantang.mogencloud.com/web/api/login/code?phone=你的手机号码"`
> 
> 看看错误日志是什么
> 
> 

![image](https://user-images.githubusercontent.com/60847880/111895036-cc9d3580-8a4a-11eb-8ccb-04de1d11dbfa.jpeg)
执行后并没有返回错误

**Comment by ericwang2006** [comment]
curl -s -k -X POST "https://tiantang.mogencloud.com/web/api/login/code?phone=你的手机号码"

增加个-k参数看看是否有效

**Comment by Ukenn2112** [comment]
>  curl -s -k -X POST "https://tiantang.mogencloud.com/web/api/login/code?phone=你的手机号码"
> 
> 增加个-k参数看看是否有效

返回这个并成功收到验证码
```
{"msg":"","errCode":0,"data":null}
```

**Comment by ericwang2006** [comment]
x86架构下可以, arm架构下似乎有问题, 我下个版本修改一下

**Comment by ericwang2006** [comment]
更新一下吧，应该解决了

**Comment by Ukenn2112** [comment]
> 更新一下吧，应该解决了

成功了，非常感谢
