### ISSUE TITLE
最新的甜糖程序一直在报错

### ISSUE THREAD

**Issue by endless1651** [ericwang2006/docker_ttnode#44]
sh: 1: killall: not found，不知道是什么问题

**Comment by ericwang2006** [comment]
这代表了ttnode的抗争, 我不让它启动ipdbcf, 稍安勿躁, 待老衲收了它!

**Comment by ericwang2006** [comment]
更新最新镜像，可以了

**Comment by endless1651** [comment]
收到，回去就更新

**Comment by whave** [comment]
请问一下大大，OPENWRT下的DOCKER运行TTNODE，怎么更新啊？重新PULL一次就可以了吗？

**Comment by ericwang2006** [comment]
> 请问一下大大，OPENWRT下的DOCKER运行TTNODE，怎么更新啊？重新PULL一次就可以了吗？

先pull, 然后删除容器, 再重新创建

**Comment by endless1651** [comment]
更新后没遇到报错了，完美
