### ISSUE TITLE
用最新的镜像出现这个报错，大佬是什么原因

### ISSUE THREAD

**Issue by lidy2007** [ericwang2006/docker_ttnode#45]
sh: 1: killall: not found

**Comment by ericwang2006** [comment]
这代表了ttnode的抗争, 我不让它启动ipdbcf, 稍安勿躁, 待老衲收了它!

**Comment by qiao112** [comment]
> 这代表了ttnode的抗争, 我不让它启动ipdbcf, 稍安勿躁, 待老衲收了它!

大佬怎么样了

**Comment by ericwang2006** [comment]
更新，可以了

**Comment by wilsonxu123** [comment]
在线更新也出现同样问题sh: 1: killall: not found

**Comment by lucktu** [comment]
我是进入甜糖后，运行下面的代码，（docker logs xxx）发现确实还有
echo '#!/bin/bash' >/usr/bin/killall && chmod +x /usr/bin/killall
