### ISSUE TITLE
ipdbcf 问题0123容器文件夹会自动的删除ipdbcf而4567则不会

### ISSUE THREAD

**Issue by qiao112** [ericwang2006/docker_ttnode#46]
![image](https://user-images.githubusercontent.com/45731546/112140543-1767aa80-8c0f-11eb-9618-d5590fcb667d.png)
![image](https://user-images.githubusercontent.com/45731546/112140552-1898d780-8c0f-11eb-8995-583e3225f542.png)

**Comment by qiao112** [comment]
我线路比较多一条线一个容器,现在网络和端口映射都正常,0123都正常跑但是4567一直没反应

**Comment by ericwang2006** [comment]
你用的可能不是我最新版本的镜像, 最新版本的镜像会在缓存目录(.yfnode同级)生成一个假的ipdbcf文件,并且(在容器内部)禁止删除
如果端口确定是通的, 缓存调度是个玄学问题, 我可能帮不到你

**Comment by qiao112** [comment]
![image](https://user-images.githubusercontent.com/45731546/112145178-03bf4280-8c15-11eb-8c5a-69533b115c64.png)
sh是这个吗

**Comment by qiao112** [comment]
我疑惑的是为什么前四个容器里面没有这个文件
![image](https://user-images.githubusercontent.com/45731546/112145258-19346c80-8c15-11eb-80a8-9f50eae975fb.png)

**Comment by qiao112** [comment]
只有一个.yfnode

**Comment by ericwang2006** [comment]
前4个的容器版本老, 不是最新的, 最新的会有ipdbcf文件, 建议统一更新, 我最新的镜像于2021.3.21下午发布

**Comment by qiao112** [comment]
我是统一更新的容器也确定是最新的
![Uploading image.png…]()

**Comment by qiao112** [comment]
![image](https://user-images.githubusercontent.com/45731546/112146181-3d447d80-8c16-11eb-93eb-3cfba4529421.png)

**Comment by ericwang2006** [comment]
看看缓存目录是不是可写，我暂时能想到的只有权限问题了，你可以进入容器，在缓存目录/mnts新建一个文件试试

**Comment by qiao112** [comment]
> 看看缓存目录是不是可写，我暂时能想到的只有权限问题了，你可以进入容器，在缓存目录/mnts新建一个文件试试
> 或者看看容器的日志有没有错误信息

我刚才也以为是权限问题但是已经排除了

**Comment by qiao112** [comment]
我从起了一次路由器貌似好了之前我估计是策略路由的问题
