### ISSUE TITLE
Creating ttnode ... error

### ISSUE THREAD

**Issue by linyecheng** [ericwang2006/docker_ttnode#47]
![image](https://user-images.githubusercontent.com/38659947/112181413-63c6e080-8c37-11eb-8d79-b5c65789851c.png)
大神，小白请教，不知为啥一直不行

**Comment by ericwang2006** [comment]
看看你的网卡名称是不是eth0
可以执行ifconfig 或者ip addr 查看网卡名称

**Comment by ericwang2006** [comment]
看了这个 https://bbs.hassbian.com/thread-9563-1-1.html 我似乎明白了
你是不是N1刷的openwrt固件做的旁路由?
如果是这个情况, 你尝试取消lan口的桥接
![qiao](https://user-images.githubusercontent.com/19389876/113242271-26232100-92e3-11eb-9729-dbaad05584ca.jpg)
那个为指定接口创建桥接的勾不打
