### ISSUE TITLE
无法启动容器

### ISSUE THREAD

**Issue by xz950211** [ericwang2006/docker_ttnode#48]
错误提示Containers: start ttnode...code:500 failed to create default sandbox: namespace creation reexec command failed: exit status 1

r2s 天灵固件

**Comment by xz950211** [comment]
方法二会出现这个错误Containers: start ttnode...code:500 OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:352: getting the final child's pid from pipe caused: EOF: unknown

**Comment by xz950211** [comment]
![image](https://user-images.githubusercontent.com/25702006/112598383-74e73b80-8e49-11eb-90b3-bfd118fdfd20.png)

**Comment by ericwang2006** [comment]
主机是什么系统?
