### ISSUE TITLE
N1 docker运行，需要进入容器手动安装traceroute.

### ISSUE THREAD

**Issue by linsongze** [ericwang2006/docker_ttnode#49]
可能是个例，我在n1 下用docker运行镜像容器，docker logs ttnode 会看到，traceroute命令找不到，而且设备会离线，只有进去容器 apt-get update & apt-get install traceroute才能够启动成功。

**Comment by ericwang2006** [comment]
traceroute只是一个网络追踪工具，应该没啥影响啊

**Comment by linsongze** [comment]
好吧.可能是其他问题导致的，也没细究了.

**Comment by wtser** [comment]
![image](https://user-images.githubusercontent.com/2093743/115642350-59d6f100-a34d-11eb-92cb-b36640c15194.png)
我这里也复现了

**Comment by ericwang2006** [comment]
目测ttnode运行时会从服务器下载shell脚本,可能不同的环境会下载不同的shell脚本,下个版本的镜像还是加上traceroute命令吧

**Comment by ericwang2006** [comment]
下个版本加上

Finn ***@***.***> 于 2021年4月22日周四 09:30写道：

**Comment by ericwang2006** [comment]
> 可能是个例，我在n1 下用docker运行镜像容器，docker logs ttnode 会看到，traceroute命令找不到，而且设备会离线，只有进去容器 apt-get update & apt-get install traceroute才能够启动成功。

目前最新镜像(v198)已经集成traceroute了,你可以更新测试一下

**Comment by linsongze** [comment]
ok.谢谢大佬。
