### ISSUE TITLE
【求助】我无法安装镜像

### ISSUE THREAD

**Issue by q4w5e6** [ericwang2006/docker_ttnode#5]
root@N1:~# **docker pull ericwang2006/ttnode**

Using default tag: latest
latest: Pulling from ericwang2006/ttnode
0321b5753c35: Extracting [==================================================>]  25.86MB/25.86MB
9e6d48305a82: Download complete 
0e510fdd5797: Download complete 
**failed to register layer: ApplyLayer exit status 1 stdout:  stderr: write /usr/share/zoneinfo/America/Fort_Wayne: no space left on device**

然而744开头的那个镜像我能够安装啊😥
root@N1:# docker pull 744287383/linux-arm64-ttnode
Using default tag: latest
latest: Pulling from 744287383/linux-arm64-ttnode
e21d51d128ea: Pull complete 
1082593b59bc: Pull complete 
Digest: sha256:251270b86ac1334247e7f3a88d303549061ebc6f39d4128fc4e2b7e26272c8ca
Status: Downloaded newer image for 744287383/linux-arm64-ttnode:latest
docker.io/744287383/linux-arm64-ttnode:latest
root@N1:#

**Comment by ericwang2006** [comment]
no space left on device  磁盘没有空间了

**Comment by q4w5e6** [comment]
> no space left on device 磁盘没有空间了

![image](https://user-images.githubusercontent.com/51695264/103474398-5ccdc600-4dde-11eb-865c-b2022d281ac7.png)
我知道问题在哪里了，谢谢大神！！
