### ISSUE TITLE
同一个目录能同时映射给多个TT DOCKER吗？

### ISSUE THREAD

**Issue by lbsystem** [ericwang2006/docker_ttnode#50]
这样不就可以节约硬盘容量又同享缓存了！！ 希望大神回答

**Comment by ericwang2006** [comment]
你可以参考一下这个帖子 https://www.right.com.cn/forum/thread-4048219-1-1.html ,看"docker容器共享缓存方法"部分就可以了
不过我不建议这么做，因为不同的容器可能同时写一个缓存目录，可能造成意想不到的问题

其实overlay文件系统可以比较完美的解决这个问题，如果你知道什么是overlay估计你马上就知道怎么做了
等我有空写个教程吧，也不知道啥时候有空，就当我没说吧

**Comment by ericwang2006** [comment]
> 这样不就可以节约硬盘容量又同享缓存了！！ 希望大神回答

教程来了 https://www.right.com.cn/forum/thread-4106166-1-1.html

**Comment by lbsystem** [comment]
太感激大神了谢谢谢谢
