### ISSUE TITLE
断网后uid失效

### ISSUE THREAD

**Issue by Luz233** [ericwang2006/docker_ttnode#51]
arm64和x86似乎都存在这个问题，断网后重新连接，客户端已经绑定的设备永远处于未配置网络状态，局域网扫描一下发现已经生成了新的UID，需要重新绑定，但并非每次断网都会这样。

**Comment by ericwang2006** [comment]
确实在论坛中看到有人反映有这个现象，而且不仅是我的镜像，目前我这里倒是没有复现出来
目前我所了解的和uid有关的因素有以下2个
1. mac地址
2. hostname
重点看看这两项是否有变化

另外你具体描述一下你的使用环境和运行的模式，观察一下uid变化是否有规律
