### ISSUE TITLE
更改映射目录后提示cannot access

### ISSUE THREAD

**Issue by engineerlzk** [ericwang2006/docker_ttnode#53]
如题，我是在unraid中以docker方式安装的，安装命令如下：
docker run -itd \
  -v /mnt/data/ttnode:/mnt/user/appdata/ttnode \
  -v /config:/mnt/user/appdata/ttnode/config \
  --name ttnode \
  --hostname ttnode4125B \
  --net=host \
  --privileged=true \
  --restart=always \
  ericwang2006/ttnode

然后容器倒是启动了，但甜糖不工作，在日志中出现如下错误：storage [/mnts],dev [/mnts] cannot access
![挂载目录出错](https://user-images.githubusercontent.com/1411044/113862072-87af2800-97da-11eb-9f76-0968f671b393.jpg)
请问应该如何解决？谢谢指教！

**Comment by ericwang2006** [comment]
-v /mnt/data/ttnode:/mnt/user/appdata/ttnode
-v /config:/mnt/user/appdata/ttnode/config
这两处冒号前是主机的目录, 冒号后是docker容器内的目录, 必须固定写/mnts和/config
你可以参考下面的写法

```
docker run -itd \
-v <主机缓存目录>:/mnts \
-v <主机配置目录>:/config \
--name ttnode \
--hostname ttnode4125B \
--net=host \
--privileged=true \
--restart=always \
ericwang2006/ttnode
```

**Comment by engineerlzk** [comment]
谢谢！居然给写反了😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月7日(周三) 晚上10:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ericwang2006/docker_ttnode] 更改映射目录后提示cannot access (#53)




 
-v /mnt/data/ttnode:/mnt/user/appdata/ttnode
 -v /config:/mnt/user/appdata/ttnode/config
 这两处冒号前是主机的目录, 冒号后是docker容器内的目录, 必须固定写/mnts和/config
 你可以参考下面的写法
 docker run -itd \ -v <主机缓存目录&gt;:/mnts \ -v <主机配置目录&gt;:/config \ --name ttnode \ --hostname ttnode4125B \ --net=host \ --privileged=true \ --restart=always \ ericwang2006/ttnode
