### ISSUE TITLE
爱快软路由Docker跑甜糖的问端口映射问题

### ISSUE THREAD

**Issue by lzqd** [ericwang2006/docker_ttnode#54]
爱快软路由Docker跑甜糖的问端口映射问题
upnp无法触发，设置端口映射后甜糖app显示未配置网络

**Comment by ericwang2006** [comment]
爱快upnp无效的,需要手动映射端口,如果确认端口映射没有问题,看看是不是没有等足够长的时间, 甜糖客户端不会实时刷新的

**Comment by lzqd** [comment]
> 爱快upnp无效的，需要手动映射端口，如果确认端口映射没有问题，看看是不是没有等足够长的时间，甜糖客户端不会实时刷新的

端口映射是每个端口独立映射还是可以一起？

**Comment by ericwang2006** [comment]
> > 爱快upnp无效的，需要手动映射端口，如果确认端口映射没有问题，看看是不是没有等足够长的时间，甜糖客户端不会实时刷新的
> 
> 端口映射是每个端口独立映射还是可以一起？

同一端口号的tcp和udp可以一起映射, 别人的教程你可以参考 https://www.5v13.com/mesh/28836.html

**Comment by lzqd** [comment]
> > > 爱快upnp无效的，需要手动映射端口，如果确认端口映射没有问题，看看是不是没有等足够长的时间，甜糖客户端不会实时刷新的
> > 
> > 
> > 端口映射是每个端口独立映射还是可以一起？
> 
> 同一端口号的tcp和udp可以一起映射, 别人的教程你可以参考 https://www.5v13.com/mesh/28836.html

就是说多个端口不能一起映射是吗？

**Comment by ericwang2006** [comment]
> > > > 爱快upnp无效的，需要手动映射端口，如果确认端口映射没有问题，看看是不是没有等足够长的时间，甜糖客户端不会实时刷新的
> > > 
> > > 
> > > 端口映射是每个端口独立映射还是可以一起？
> > 
> > 同一端口号的tcp和udp可以一起映射, 别人的教程你可以参考 https://www.5v13.com/mesh/28836.html
> 
> 就是说多个端口不能一起映射是吗？

建议你看教程

**Comment by lzqd** [comment]
> > > > > 爱快upnp无效的，需要手动映射端口，如果确认端口映射没有问题，看看是不是没有等足够长的时间，甜糖客户端不会实时刷新的
> > > > 
> > > > 
> > > > 端口映射是每个端口独立映射还是可以一起？
> > > 
> > > 
> > > 同一端口号的tcp和udp可以一起映射, 别人的教程你可以参考 https://www.5v13.com/mesh/28836.html
> > 
> > 
> > 就是说多个端口不能一起映射是吗？
> 
> 建议你看教程

好吧
