### ISSUE TITLE
关于UPNP 和多线路的分流问题

### ISSUE THREAD

**Issue by lbsystem** [ericwang2006/docker_ttnode#55]
最近查看nf_conntrack 发现 下在多条外网线路的情况下 就算你做好策略路由 如果使用UPNP  upnp 只会分配默认线路的映射 导致线路分配混乱,, 请问大神有何办法解决 (现在在使用OPENWRT)

**Comment by ericwang2006** [comment]
多线路没研究过，感觉upnp应该是不能用，只能手动做端口映射了。这方面无法给你很好的建议。

**Comment by lbsystem** [comment]
能用是能用只是 miniUPNP 只支持默认路由  我现在只能用用connmark 做路由控制 因为不知道miniupnp 到底是怎么标志数据包的怕导致混乱. TT这个东西真顽固 明明已经是FULL CONE了还必须要支持upnp 不然不给流量.唉........

**Comment by ericwang2006** [comment]
其实是可以关闭upnp，完全通过iptables命令完成端口映射的
下面的语句你可以参考一下，因为不同的系统情况不同，iptables防火墙规则的顺序非常关键,要合理安排执行顺序
我也没有多线路环境，所以我也没办法测试，你自己试一下吧，不确定完全可行，但感觉理论可以
```
wan_dev='pppoe-wan' # 外网接口

iptables -t nat -A PREROUTING -i $wan_dev -p tcp -m tcp --dport 25235 -j DNAT --to-destination 192.168.2.32
iptables -A FORWARD -d 192.168.2.32/32 -i $wan_dev -p tcp -m tcp --dport 25235 -j ACCEPT

iptables -t nat -A PREROUTING -i $wan_dev -p udp -m udp --dport 25235 -j DNAT --to-destination 192.168.2.32
iptables -A FORWARD -d 192.168.2.32/32 -i $wan_dev -p udp -m udp --dport 25235 -j ACCEPT

iptables -t nat -A POSTROUTING -s 192.168.2.0/24 -o $wan_dev -j MASQUERADE
```

**Comment by q398044828** [comment]
> 最近查看nf_conntrack 发现 下在多条外网线路的情况下 就算你做好策略路由 如果使用UPNP upnp 只会分配默认线路的映射 导致线路分配混乱,, 请问大神有何办法解决 (现在在使用OPENWRT)

可以配置负载均衡,当源ip为甜糖内网ip时，走某个固定的wan口

**Comment by ericwang2006** [comment]
> > 最近查看nf_conntrack 发现 下在多条外网线路的情况下 就算你做好策略路由 如果使用UPNP upnp 只会分配默认线路的映射 导致线路分配混乱,, 请问大神有何办法解决 (现在在使用OPENWRT)
> 
> 可以配置负载均衡,当源ip为甜糖内网ip时，走某个固定的wan口

设置某个ip固定走某个wan口也不能代替端口映射, 
设置好了后还是需要我那几个iptables命令来代替端口映射(关闭upnp)

**Comment by BCYDTZ** [comment]
建议可以关闭tt的upnp😳
