### ISSUE TITLE
运行一段时间，测速带宽会严重低于实际带宽

### ISSUE THREAD

**Issue by q398044828** [ericwang2006/docker_ttnode#56]
斐讯N1刷的小钢炮，
软路由3拨，N1启动3个docker容器，负载均衡各使用1拨
经常运行一段时间后，50M的上行带宽，测速带宽只有20多M，服务带宽只有几M，重启后，测速带宽恢复正常

**Comment by ericwang2006** [comment]
情况太复杂，超出我的能力范围。建议先从单拨单容器开始测试，不断增加容器数量或拨号连接数量，看看什么因素影响最大。另外n1跑三个容器可能有点吃力，甜糖挺占内存的。

**Comment by q398044828** [comment]
> 情况太复杂，超出我的能力范围。建议先从单拨单容器开始测试，不断增加容器数量或拨号连接数量，看看什么因素影响最大。另外n1跑三个容器可能有点吃力，甜糖挺占内存的。

这两天测试了单节点，只启动一个节点，还是有同样的问题

**Comment by ericwang2006** [comment]
> > 情况太复杂，超出我的能力范围。建议先从单拨单容器开始测试，不断增加容器数量或拨号连接数量，看看什么因素影响最大。另外n1跑三个容器可能有点吃力，甜糖挺占内存的。
> 
> 这两天测试了单节点，只启动一个节点，还是有同样的问题

我估计即使直接用官方的程序跑(不用docker),可能也有类似的问题
暂时没有什么思路了

**Comment by lqzhgood** [comment]
诶~ 最近我也是
更新194以后就是这样了  x86 pc 在跑

**Comment by ericwang2006** [comment]
> 诶~ 最近我也是
> 更新194以后就是这样了 x86 pc 在跑

docker镜像没有特别处理,只是更新了二进制文件

**Comment by q398044828** [comment]
> 诶~ 最近我也是
> 更新194以后就是这样了 x86 pc 在跑

对 我也是从v194开始的，估计就是官方程序问题，现在v197没这个问题了
