### ISSUE TITLE
优化docker-compose文件

### ISSUE THREAD

**Issue by trainliang** [ericwang2006/docker_ttnode#58]
## 问题
使用docker-compose重新启动节点node时会出现配置的coookie丢失无法自动收星，无法通知

## 建议
1. 添加一下macvlan模式下多node的docker-compose文件
2. ~~将配置写在持久化文件中~~，将config的路径配置放在首页文档， 同时添加检测cookie失效时间，在即将失效前通知一下
3. 建议主推docker-compose方式部署，因为docker run方式不利于手动重启与迁移

**Comment by ericwang2006** [comment]
目前没有测试出重启容器丢失cookie的情况(需要把/config映射到主机路径)
目前token失效会有通知, 会提示"token可能失效，请尝试重新登录。"(提前通知没有做)
其他问题属于优化,有时间再考虑吧
