### ISSUE TITLE
failed to create the macvlan port: operation not supported

### ISSUE THREAD

**Issue by edison0354** [ericwang2006/docker_ttnode#61]
您好，

我拨号的光猫是192.168.1.1，下面插着R2S是192.168.1.11，docker跑在R2S上面

按下面这样跑的，192.168.1.7确认没有被占用
ip link set eth0 promisc on
docker network create -d macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 -o parent=eth0 -o macvlan_mode=bridge macnet
docker run -itd \
  -v /mnt/usb/ttnode:/mnts \
  --name ttnode2 \
  --hostname ttnode2 \
  --net=macnet --ip=192.168.1.7 --dns=114.114.114.114 --mac-address C2:F2:9C:C5:B2:94 \  
  --privileged=true \
  --restart=always \
  ericwang2006/ttnode

然后就报下面错误，手动运行也一样，请问这是什么情况？谢谢！
docker: Error response from daemon: failed to create the macvlan port: operation not supported.

另外还有个玄学，光猫已经给R2S开了DMZ，手机连着R2S，用甜糖APP测已经是优质网络了，但如果ttnode按方法二直接泡在docker里，还是未配置……按理说手机都比这个docker多一层了啊，有什么需要排查的地方么？

**Comment by ericwang2006** [comment]
1. 你的R2S是刷的OpenWrt系统吧, 如果是OpenWrt, , 网口名称默认是br-lan , 因为是桥接的,  创建macvlan时这样写
`docker network create -d macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 -o parent=br-lan -o macvlan_mode=bridge macnet`
你需要删除已经创建的macvlan和容器, 重新来一次

2. 我不知道你的R2S做的是旁路由还是二级路由, 如果是二级路由还需要在R2S上手动做一次端口映射(如果R2S的UPNP没生效)

**Comment by edison0354** [comment]
emm...抱歉还是不行……

我的网络是这样的

- 移动光猫（192.168.1.1）
- R2S，二级路由
  - 上面光猫对它做了DMZ，所以它理论上是暴露在移动内网里面的，实际用手机APP测下来应该也是
  - wan口是eth0, 192.168.1.11
  - lan口是br-lan, 192.168.0.1
  - Docker跑在这上面
 - R2S的LAN口插在无线路由（192.168.0.2）的LAN口上，只做AP，跟网络本身应该没啥关系
 - 下面所有无线设备都在192.168.0.0/24里面

然后我各种乱七八糟又试了一通，还是一直是同样的错误

`docker: Error response from daemon: failed to create the macvlan port: operation not supported.`

于是：

- 上面您说应该桥接在lan口上，那么对应IP网关是不是也应该是我这边的192.168.0.1系列？
- 下面docker运行时候指定IP应该是在哪个网段里面？

其实我似乎已经把上面各种排列组合都试过了orz

还有如果不建macvlan直接跑的话：

- 理论上应该已经是在移动内网了吧？
- 用手机APP测，路由器上看到upnp是生效了的，而且“网络极佳”。实际甚至连bilibili的手机app都注册了个端口，虽然我也不知道它用来干啥的……
- 然而docker上的ttnode还是未配置网络
- 莫非应该在R2S上端口转发到docker自动生成的那个bridge的172.17.0.0/16里面？

谢谢！

**Comment by ericwang2006** [comment]
我建议你不要搞二级路由, 二级路由要两次转发(光猫到R2S开DMZ,  R2S要开UPNP,如果不生效还要端口映射)

做旁路由你可以直接用一根网线把光猫的LAN口和R2S的LAN口连接就可以

**你的macvlan没有创建成功,先删除已经创建的macvlan和容器**

以下是做旁路由的设置方法:

- 到lan口的物理设置中取消桥接

![修改接口](https://user-images.githubusercontent.com/19389876/117094646-e5fa0700-ad96-11eb-960a-363beff0ca80.png)
![接口3](https://user-images.githubusercontent.com/19389876/117094650-ebefe800-ad96-11eb-96a8-0d4afc2b35b8.png)

- 给LAN口设置一个固定的IP(192.168.1.X)和网关(192.168.1.1), dns也填192.168.1.1

- 然后创建macvlan的时候父接口就填eth0
`docker network create -d macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1 -o parent=eth0 -o macvlan_mode=bridge macnet`

不知道你的光猫有没有UPNP, 如果没有就手动端口映射
这样测试一下

**Comment by ericwang2006** [comment]
另外这个报错我没见过，是不是你的系统缺少macvlan的驱动，我还不能确定。

**Comment by edison0354** [comment]
多谢提醒，我居然没装kmod-macvlan……蠢死了……

现在OK了，还是跑的二级路由，桥接到R2S的wan口之后，直接就优质节点了，连端口映射都不需要做。

但测试了下直接方法二本机跑，还是不行，迷，不管了……
