### ISSUE TITLE
关于UPNP 和多线路的分流问题

### ISSUE THREAD

**Issue by BCYDTZ** [ericwang2006/docker_ttnode#64]
在多条外网线路的情况下 做好策略路由 如果使用UPNP upnp 只会分配默认线路的映射 导致线路分配混乱,miniUPNP 只支持默认路由,但是我又没办法关闭upnp功能，因为其他软件在用upnp，建议还是x86的tt不要修复upnp了，还是采用端口转发这个吧。

**Comment by ericwang2006** [comment]
你可以试试  ericwang2006/ttnode:x86_arm64   这个镜像, 这个是x86下模拟arm64,  正好不支持upnp

**Comment by BCYDTZ** [comment]
那这个镜像在哪里？

**Comment by ericwang2006** [comment]
> 那这个镜像在哪里？

hub.docker.com
~~~
docker pull ericwang2006/ttnode:x86_arm64
~~~

**Comment by BCYDTZ** [comment]
> > 那这个镜像在哪里？
> 
> hub.docker.com
> 
> ```
> docker pull ericwang2006/ttnode:x86_arm64
> ```

这个镜像的upnp也是起作用的。。。。

**Comment by ericwang2006** [comment]
你在upnp设置中禁用你容器的ip吧, 可以单独根据ip来禁用

**Comment by BCYDTZ** [comment]
> 你在upnp设置中禁用你容器的ip吧, 可以单独根据ip来禁用
> ![upnp](https://user-images.githubusercontent.com/19389876/120883634-ce6da280-c610-11eb-8be0-41684192893c.png)

我尝试过这个方案，好像这样以后，端口转发都不能用了🤣🤣🤣
