### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by hx210** [ericwang2006/docker_ttnode#67]
2021-06-05 14:34:49.000 storage [/mnts],dev [/mnts] cannot access
之前的版本无法获取token了，删除了配置 装最新
新版本试了几次 桥接 host都报错
求解

**Comment by ericwang2006** [comment]
缓存目录不能访问

**Comment by hx210** [comment]
我直接用的sd卡做缓存
docker run -itd \
  -v /mnt/data/ttnode:/opt/data/ttnode/tt0 \
  --name ttnode0 \
  --hostname ttnode0 \
  --net=host \
  --privileged=true \
  --restart=always \
  ericwang2006/ttnode



/dev/mmcblk0p3 | /opt | 28.27 GB / 116.01 GB | 74% (81.81 GB) | &nbsp;
-- | -- | -- | -- | --
/dev/mmcblk0p3 | /opt/docker | 28.27 GB / 116.01 GB | 74% (81.81 GB)



直接挂载在opt分区

**Comment by ericwang2006** [comment]
> 我直接用的sd卡做缓存
> docker run -itd \
>   -v /mnt/data/ttnode:/opt/data/ttnode/tt0 \
>   --name ttnode0 \
>   --hostname ttnode0 \
>   --net=host \
>   --privileged=true \
>   --restart=always \
>   ericwang2006/ttnode
> 
> 
> 
> /dev/mmcblk0p3 | /opt | 28.27 GB / 116.01 GB | 74% (81.81 GB) | &nbsp;
> -- | -- | -- | -- | --
> /dev/mmcblk0p3 | /opt/docker | 28.27 GB / 116.01 GB | 74% (81.81 GB)
> 
> 
> 
> 直接挂载在opt分区

 -v /mnt/data/ttnode:/mnts 
冒号前面是你sd卡路径，冒号后面固定写/mnts

**Comment by hx210** [comment]
好的我这就改

**Comment by hx210** [comment]
成功运行了 谢谢你
