### ISSUE TITLE
缓存为0

### ISSUE THREAD

**Issue by inbogota** [ericwang2006/docker_ttnode#68]
Debian，host模式，upnp全通，24小时了缓存仍然为0

手动设置把/mnt映射出来的，外部目录给了 777 权限

这样的情况可能是什么原因？

**Comment by ericwang2006** [comment]
如果手机上显示网络类型0，并且目录确定是可写的，大概率就不是你的问题，是缓存下载慢的问题，很多人好几天都没下载下来，你可以问问官方客服。
