### ISSUE TITLE
x86_arm64虽然作者明确说不支持upnp,,但我反倒就这个镜像能upnp

### ISSUE THREAD

**Issue by iso-lib** [ericwang2006/docker_ttnode#69]
环境x86,PVE软路由,自编译openwrt 19.07,内核4.14

alpine系统,安装docker,用作者默认的甜糖镜像upnp没啥动静,,,只能端口转发或者防火墙规则

而用x86_arm64镜像则upnp立马显示了各个端口

各位自行测试,,猜测跟openwrt内核有关,,我用的4.14内核比较老

**Comment by ericwang2006** [comment]
大家可以测试一下，可以反馈一下，我这里测试的结果是x86模拟arm32（默认镜像配置），UPnP可正常工作，x86模拟arm64，UPnP不能正常工作。

**Comment by star-o0O** [comment]
模拟arm64可以UPNP，用的爱快

**Comment by ericwang2006** [comment]
新的alpine版本有原生x86支持, 大家可以测试一下

**Comment by gujiangjiang** [comment]
@ericwang2006 我是x86黑群晖的Docker运行，一直用您之前的latest版本，NAT0，一直也没问题，今天删掉了Docker重新测试了您的alphine版本，一直提示NAT4，尴尬了，不知道咋回事。。。

**Comment by Misaka-Biu** [comment]
我这边群晖直接docker host相同网络 x86_arm64 UPnP 也正常

**Comment by shikkoku** [comment]
各位，alphine的x86原生版本 upnp正常吗？

**Comment by ericwang2006** [comment]
> 环境x86,PVE软路由,自编译openwrt 19.07,内核4.14
> 
> alpine系统,安装docker,用作者默认的甜糖镜像upnp没啥动静,,,只能端口转发或者防火墙规则
> 
> 而用x86_arm64镜像则upnp立马显示了各个端口
> 
> 各位自行测试,,猜测跟openwrt内核有关,,我用的4.14内核比较老
> 
> 

如果没啥特殊需求，建议用官方openwrt版会好一些
