### ISSUE TITLE
wget https://cdn.jsdelivr.net/gh/ericwang2006/docker_ttnode/build_dir/ttnode_task.sh这儿报错是什么情况

### ISSUE THREAD

**Issue by MoPoQAQ** [ericwang2006/docker_ttnode#7]
root@ttnode:/usr/node# wget https://cdn.jsdelivr.net/gh/ericwang2006/docker_ttnode/build_dir/ttnode_task.sh
--2021-01-11 14:16:57--  https://cdn.jsdelivr.net/gh/ericwang2006/docker_ttnode/build_dir/ttnode_task.sh
Resolving cdn.jsdelivr.net (cdn.jsdelivr.net)... 121.18.212.135
Connecting to cdn.jsdelivr.net (cdn.jsdelivr.net)|121.18.212.135|:443... connected.
ERROR: The certificate of ‘cdn.jsdelivr.net’ is not trusted.
ERROR: The certificate of ‘cdn.jsdelivr.net’ doesn't have a known issuer.

**Comment by MoPoQAQ** [comment]
解决了： wget https://cdn.jsdelivr.net/gh/ericwang2006/docker_ttnode/build_dir/ttnode_task.sh --no-check-certificate

**Comment by ericwang2006** [comment]
也可以尝试
```
apt-get update
apt-get install ca-certificates
wget https://cdn.jsdelivr.net/gh/ericwang2006/docker_ttnode/build_dir/ttnode_task.sh
```
试一下
