### ISSUE TITLE
X86_64原生软件包

### ISSUE THREAD

**Issue by star-o0O** [ericwang2006/docker_ttnode#70]
甜糖刚出了X86_64的ipk包，E大能否研究下，感谢大佬
[ttnode_openwrt_x86_64.zip](https://github.com/ericwang2006/docker_ttnode/files/6660166/ttnode_openwrt_x86_64.zip)

**Comment by ericwang2006** [comment]
这个可以有

**Comment by Zy143L** [comment]
> 这个可以有

补全lib库 就可以在其他x86 Linux下跑了
![image](https://user-images.githubusercontent.com/21352718/122202107-49677080-cecf-11eb-882d-23c74a2e3fba.png)

**Comment by ericwang2006** [comment]
> > 这个可以有
> 
> 补全lib库 就可以在其他x86 Linux下跑了
> ![image](https://user-images.githubusercontent.com/21352718/122202219-656b1200-cecf-11eb-803c-08eab2555785.png)
> 
> 

如果是OpenWrt下能跑，大概率是musl c,或许alpine下可以直接跑，这几天有点忙，晚点搞一下。

**Comment by Zy143L** [comment]
> > > 这个可以有
> > 
> > 
> > 补全lib库 就可以在其他x86 Linux下跑了
> > ![image](https://user-images.githubusercontent.com/21352718/122202219-656b1200-cecf-11eb-803c-08eab2555785.png)
> 
> 如果是OpenWrt下能跑，大概率是musl c,或许alpine下可以直接跑，这几天有点忙，晚点搞一下。

在docker下的alpine跑了下 还是存在吃内存的情况...跑了2个小时 吃了4g+了

**Comment by ericwang2006** [comment]
已经发布alpine版, 可以试一下了, 参看Readme的alpine版部分

**Comment by Zy143L** [comment]
> 已经发布alpine版, 可以试一下了, 参看Readme的alpine版部分

你那边测试 内存占用怎么样呢
我这边内存占用 比arm的小一些..但是还是很吃
CPU占用的改善很大
![image](https://user-images.githubusercontent.com/21352718/122639145-b6c30d80-d12a-11eb-87b0-59453df36d1e.png)
缓存问题..从新生成config cache可以继续用
甜糖要扫盘 很久才能识别到

**Comment by ericwang2006** [comment]
> > 已经发布alpine版, 可以试一下了, 参看Readme的alpine版部分
> 
> 你那边测试 内存占用怎么样呢
> 我这边内存占用 比arm的小一些..但是还是很吃
> CPU占用的改善很大
> ![image](https://user-images.githubusercontent.com/21352718/122639145-b6c30d80-d12a-11eb-87b0-59453df36d1e.png)
> 缓存问题..从新生成config cache可以继续用
> 甜糖要扫盘 很久才能识别到

我删除config试试，没下载下来缓存还没测试内存占用。

**Comment by yangjiemong2** [comment]
> > > 已经发布alpine版, 可以试一下了, 参看Readme的alpine版部分
> > 
> > 
> > 你那边测试 内存占用怎么样呢
> > 我这边内存占用 比arm的小一些..但是还是很吃
> > CPU占用的改善很大
> > ![image](https://user-images.githubusercontent.com/21352718/122639145-b6c30d80-d12a-11eb-87b0-59453df36d1e.png)
> > 缓存问题..从新生成config cache可以继续用
> > 甜糖要扫盘 很久才能识别到
> 
> 我删除config试试，没下载下来缓存还没测试内存占用。

我跑了一晚，删了config，用的老缓存。现在内存已经占用4G多了。。比QEMU版的还高。。。
![image](https://user-images.githubusercontent.com/41184957/131610382-42ee8324-d62d-44f0-8eb1-95235855efa7.png)

**Comment by ericwang2006** [comment]
目前甜糖官方已经出了docker, 建议使用官方的测试一下

**Comment by yangjiemong2** [comment]
好的，感谢。
