### ISSUE TITLE
不自动收取星愿

### ISSUE THREAD

**Issue by lukemin** [ericwang2006/docker_ttnode#73]
config.json
{
  "sckey": "",
  "tg_api_key": "",
  "tg_chat_id": "",
  "tg_proxy": "",
  "auto_turbo": "1",
  "auto_withdraw": "1",
  "token": "null"
}

crontab_list.sh

0 0 * * *  /usr/node/ttnode_task.sh update
8 20 * * * /usr/node/ttnode_task.sh auto_turbo
8 4 * * *  /usr/node/ttnode_task.sh report
15 4 * * 3 /usr/node/ttnode_task.sh withdraw

**Comment by ericwang2006** [comment]
要先到甜糖面板"获取cookie"页, 登陆一次,获取cookie, 获取后config.json中的toke就是非空的了,这样才能自动收割
