### ISSUE TITLE
手机里缓存移到群晖上，具体要怎么弄？

### ISSUE THREAD

**Issue by sd462355991111** [ericwang2006/docker_ttnode#75]
我手机挂了很久tt  现在缓存有85g了，快把手机撑满。 主要是有量，没量我也不折腾。
现在我想把它移到群晖上面去，
是不是手机里
tiantangND_android-----cache
tiantangND_android-----config
都移动群晖
.yfnode-----cache
.yfnode-----config
config跟config都移动对吗？要不要改什么文件之类的，还是怎么样，望回答下。

**Comment by ericwang2006** [comment]
1.停止容器
2. 复制手机cache目录到群晖 .yfnode-----cache
3. 删除群晖.yfnode-----config(如果有)
4. 启动容器,重新绑定设备(uid可能会变)
5. 请先做好数据备份工作
