### ISSUE TITLE
缓存113G，内存要用到1.3G，请问正常吗？

### ISSUE THREAD

**Issue by TankMing** [ericwang2006/docker_ttnode#79]
设备是N1，挂了几个月吧，100M上传，起码跑了70Mbps的上传。
一旦限制内存，过一段时间就会提示找不到ttnode进程，然后自动重启，现在只能不限制。目前是debian的latest版本，感觉资源占用过高，有必要清空缓存重新来吗？感谢

**Comment by ericwang2006** [comment]
1.3g内存占用不算多了，可以说偏少了，缓存是可以删除些老的，效果怎么样不好说
