### ISSUE TITLE
建议把配置信息放到单独的文件夹

### ISSUE THREAD

**Issue by Dellear** [ericwang2006/docker_ttnode#8]
建议把配置文件（config.json、crontab_list.sh ）放到/config文件夹下，docker使用时，可以把配置目录映射，不必每次重建容器都要重新设置自动收星。

**Comment by ericwang2006** [comment]
有合理性，下个版本弄一下

**Comment by ericwang2006** [comment]
已经更新,参见https://github.com/ericwang2006/docker_ttnode/blob/master/AutoNode.md
