### ISSUE TITLE
获取Cookie提示登录失败

### ISSUE THREAD

**Issue by lkhtest** [ericwang2006/docker_ttnode#85]
验证码能正常接收，但是登录不了
![image](https://user-images.githubusercontent.com/27727473/131929082-b4e5ec53-eb5e-45f7-82e1-776d550b6a05.png)

**Comment by ericwang2006** [comment]
以前老版本有过这个情况,不过最新的版本我前几天还登陆过,没有发现问题.
你尝试进入容器执行下面代码试试
```
sed -i "s/https:\/\/tiantang/http:\/\/tiantang/g" /usr/node/ttnode_task.sh
sed -i "s/https:\/\/tiantang/http:\/\/tiantang/g" /usr/node/htdocs/get_info.cgi
```
