### ISSUE TITLE
内存占用过多，机器跑死

### ISSUE THREAD

**Issue by blip-glitch** [ericwang2006/docker_ttnode#86]
我在我家unraid（内存4g)上部署了甜糖容器，机器待机内存占用92%左右，两天后机器内存占用爆炸，docker容器均无反应，应该是我用qbittorrent下载的原因，希望作者能在介绍里加上内存限制选项。docker update ttnodeA --memory-swap -1 -m 1024M

**Comment by ericwang2006** [comment]
谢谢,不少人也遇到过类似情况,我在常见问题里面加一下说明吧

**Comment by ericwang2006** [comment]
已经在README的FAQ中添加说明.
