### ISSUE TITLE
更换Alpine后 几天了没一点速度

### ISSUE THREAD

**Issue by lalasou** [ericwang2006/docker_ttnode#88]
无奈更换回去吧

**Comment by ericwang2006** [comment]
更换后缓存不要删除，只需要把config删除就可以

**Comment by lalasou** [comment]
Alpine 一直没速度  换回原来的了 

大佬 Alpine能用不

**Comment by ericwang2006** [comment]
> Alpine 一直没速度 换回原来的了
> 
> 大佬 Alpine能用不

目前能用, 但是现在官方也出了docker, 建议使用官方的版本, 会得到更快的更新.

**Comment by lalasou** [comment]
甜糖原因 公告说了
