### ISSUE TITLE
树莓派3b+(raspbian)该如何使用？

### ISSUE THREAD

**Issue by someash** [ericwang2006/docker_ttnode#9]
![image](https://user-images.githubusercontent.com/32922655/104394608-ecfbd000-5581-11eb-94d4-e433f87f5d6c.png)

**Comment by ericwang2006** [comment]
你的错误日志显示/mnts不能访问，查看启动docker的命令
```
docker run -itd \
  -v /mnt/data/ttnode:/mnts \
  --name ttnode \
  --net=host \
  --privileged=true \
  --restart=always \
  ericwang2006/ttnode
```
-v 参数冒号前面的路径是否存在，磁盘空间是否够用

**Comment by someash** [comment]
磁盘空间应该够，是一张128g的tf卡（读写40m/s），我怀疑可能是我没看懂教程，
我先输入了一遍实用教程里面的代码，然后再输入了方法2的代码。。。然后把进入容器和查看uuid的代码也输进去没反应，最后输入了docker run ericwang2006/ttnode
（全是在root权限下操作的）

**Comment by ericwang2006** [comment]
> 磁盘空间应该够，是一张128g的tf卡（读写40m/s），我怀疑可能是我没看懂教程，
> 我先输入了一遍实用教程里面的代码，然后再输入了方法2的代码。。。然后把进入容器和查看uuid的代码也输进去没反应，最后输入了docker run ericwang2006/ttnode
> （全是在root权限下操作的）

`docker run ericwang2006/ttnode` 没有必要运行,运行了你可能都无法退出,只能重启主机了
要进入容器执行docker exec -it ttnode /bin/bash  ,其中ttnode是容器的名称(--name ttnode)
查看日志就在宿主机执行docker logs ttnode

**Comment by someash** [comment]
![image](https://user-images.githubusercontent.com/32922655/104430709-03298080-55c2-11eb-8e1d-f470365aad22.png)
这个 的不符会影响使用吗？

**Comment by someash** [comment]
![image](https://user-images.githubusercontent.com/32922655/104433026-906dd480-55c4-11eb-8c01-bab788b2ec9d.png)
这个问题是要去路由器设置吗？

**Comment by someash** [comment]
![image](https://user-images.githubusercontent.com/32922655/104433144-b85d3800-55c4-11eb-9dfc-05761901836a.png)
这个是要去路由器上设置吗？

**Comment by ericwang2006** [comment]
> ![image](https://user-images.githubusercontent.com/32922655/104433144-b85d3800-55c4-11eb-9dfc-05761901836a.png)
> 这个是要去路由器上设置吗？

如果甜糖客户端长时间显示网络不正常，就到路由器上设置一下，如果路由器的punp是开启的，有很大概率不用做任何设置就可以用。

**Comment by ericwang2006** [comment]
> ![image](https://user-images.githubusercontent.com/32922655/104430709-03298080-55c2-11eb-8e1d-f470365aad22.png)
> 这个 的不符会影响使用吗？

不会有影响，虽然在树莓派上根本不需要运行这个。
