### ISSUE TITLE
启动失败，求助

### ISSUE THREAD

**Issue by lxl6125** [ericwang2006/docker_ttnode#92]
[2021-11-30 02:38:18] 正在获取端口信息...
[2021-11-30 02:38:38] ttnode进程不存在,启动ttnode
version: 1.0.0.327
terminate called after throwing an instance of 'cmdline::cmdline_error'
  what():  there is no flag: --rpc
terminate called after throwing an instance of 'cmdline::cmdline_error'
  what():  there is no flag: --rpc
获取二维码失败

然后控制面板里面的 端口 和 防火墙规则 一直显示 【正在玩命加载...】

**Comment by azureology** [comment]
@lxl6125 
same + 1
image alpine x86 , app ver 1.0.0.327
尝试进container手启也报错，另一台官方docker也于今早掉线
高度怀疑app问题坐等官方更新

**Comment by FengNning** [comment]
官方更新了
