### ISSUE TITLE
ttnode程序官方更新了

### ISSUE THREAD

**Issue by 1379441534** [ericwang2006/docker_ttnode#93]

**Comment by ericwang2006** [comment]
目前官方出了docker了, 我这个项目算是完成历史使命了,应该不会继续更新了.

**Comment by Billyas** [comment]
官方通告

> 今早（11-30）更新的ttnode存在无法启动的bug，官方docker已经通过自动更新重新部署，第三方docker可以联系原作者替换最新ttnode更新部署，直接部署裸程序的用户只能手动替换最新的ttnode了，压缩包里附带的yfapp.conf必须也放置在ttnode同目录下。很抱歉给大家带来的不便，我们将在评估整体状态后尽快给出相应补偿方案！经过此次异常，强烈建议所有用户直接部署官方docker，在出现故障的情况下也可以通过自动更新解决。

解决办法就是进入容器内部，更换对应文件，即可正常运行。不用继续更新docker容器。

**Comment by shalinjie** [comment]
官方下载没看到docker呀

**Comment by ericwang2006** [comment]
> 感谢作者这么久的无私奉献，期待新项目继续支持

还是更新一下吧，现在已经发布了最新版本，没有充分测试，目前简单测试可以正常运行，如果有需要可以更新一下最新镜像。
